### ISSUE TITLE
1.16 version shows update, when no update exists

### ISSUE THREAD

**Issue by griffin4cats** [Sollace/Presence-Footsteps#100]
I got a notification from my 1.16 version of presence footsteps that an update is available (v31) but v31 is not available for 1.16.5.
I'm worried this might show every time I use the game... Is there a fix for this?
And, does it matter if I have a custom fork? I continued to use my fork of 1.16.5, which only has the pull request I made for the bipedal avian stance (a feature later added to 1.17 but not 1.16.5)

**Comment by Sollace** [comment]
It will show a few times and then stop. The update notification is there to let people know that there's a new version, whether for the same minecraft version or a newer one.
