### ISSUE TITLE
Pony step sounds don't play

### ISSUE THREAD

**Issue by ShannonW1950** [Sollace/Presence-Footsteps#101]
What it says on the tin, I've not exhaustively tested every variety yet, but alicorn and pegasus both are using bipedal walking sounds in SP, and there's no flight sounds.
Running in Linux Mint 20.2, using the Minecraft Java Edition 1.17.1 off the software manager.

Fabric is installed and I have
- fabric-api-0.37.2+1.17.jar
- minelittlepony-4.3.5.jar
- PresenceFootsteps-r32-1.17-rc1.jar
In the mods folder, and I do hear the presence footsteps sounds, and it is showing up in the output log.

A thing I do notice is yellow text for

> Mod `presencefootsteps` (r31-1.17-rc1) does not respect SemVer - comparison support is limited.

And oddly, something is reporting that I'm a batpony first and then reporting pegasus instead properly. But I'm guessing that's Mine Little Pony and _probably_ not a problem, since wing animations and everything else is fine there. The only thing wrong is hoofsteps and flying sounds that I can tell.

**Comment by Sollace** [comment]
You can check your presence footsteps settings (F10, I believe) and set your stance manually from there. It is supposed to detect it automatically, but might not in some cases.

**Comment by ShannonW1950** [comment]
Ah, that did work! Was not aware that was a thing, but my day is measurably improved by this addition to it! Thank you! Is there a way to have that added to the readme or something?

**Comment by Sollace** [comment]
tbh I kind of assumed people would already know about it. The settings menu has been around for a _long_ time.

I'll consider adding it to the readme, though.
