### ISSUE TITLE
Can servers customize this?

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#102]
I play on a server that uses plugins and s resource pack to apply custom blocks and items.
Because of this do I however face to sad issue, that some blocks will play as wooden blocks, because they are note blocks with custom data applied, while the server displays them as f.e. stone blocks or similar.

My question now is, if there is a way for the server to "tell" the mod what sound palette should be used for what specific block?

**Comment by Sollace** [comment]
Nope. I'm afraid not. Unless they can add them to a blocktag that would give it the correct sounds, you'd have to setup the sound mapping yourself with a resourcepack.

**Comment by Andre601** [comment]
Okay, thank you for the information.

There is one thing I noticed tho, which is that the sound doesn't change when you're walking on blocks that are underwater (have a source or general water block above them), which I think is a missed opportunity for additional real sounds to exist...
