### ISSUE TITLE
Sound for walking in water and/or underwater

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#103]
There doesn't seem to be sound for when you walk on blocks that are underwater (Either just one block or more).

It would be cool to have sounds for such cases too.

**Comment by Sollace** [comment]
You can already achieve this effect using the "wet" substrate. Wet applies to all blocks that are waterlogged, under water, or out in the rain.

**Comment by Andre601** [comment]
The issue is more that some sounds don't seem to play (i.e. sand) despite them being either covered by water or being under rain.
