### ISSUE TITLE
Broken Water Sound

### ISSUE THREAD

**Issue by HadrianFaerwald** [Sollace/Presence-Footsteps#104]
When swimming or in water pretty much at all, the sound for "walking/swimming" repeats non-stop and is very annoying when trying to swim in peace... Even when you're standing still and just floating down it repeats 1000 times.

**Comment by Liberato116** [comment]
Can confirm this, as a "workaround" I noticed the sound stops when you walk on a block underwater, but having to do that is pretty annoying.
