### ISSUE TITLE
Disabled all other sounds

### ISSUE THREAD

**Issue by srnyx** [Sollace/Presence-Footsteps#106]
When I used Presence Footsteps it disabled all the other sounds except for the footsteps.

**Comment by SpiffyJUNIOR** [comment]
This happens sometimes, you can fix it temporarily by bringing the master volume to 0% and then back to 100%.

**Comment by srnyx** [comment]
> This happens sometimes, you can fix it temporarily by bringing the master volume to 0% and then back to 100%.

Doesn't work for me

**Comment by Sollace** [comment]
PF has its own volume slider in its setting screen. Make sure it isn't muted there.

**Comment by srnyx** [comment]
> PF has its own volume slider in its setting screen. Make sure it isn't muted there.

It's not just PF that I can't hear though, it's the entire game (I think I could hear *some* things though, but I don't remember what).

**Comment by Sollace** [comment]
I don't think this has anything to do with Presence Footsteps then. I don't mess with any other sounds than footsteps
