### ISSUE TITLE
How can you override this with a resource pack

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#107]
I was wondering what the exact steps are you need to make in order to override what sounds are used for specific blocks...

I plan on making a resource pack that, alongside a Server RP unlocker, would override sounds for specific noteblock states, but I'm not sure what exact changes I would need to have in the RP to actually override the mods defaults.

So far, I can see that the mod has a [`blockmap.json`](https://github.com/Sollace/Presence-Footsteps/blob/master/src/main/resources/assets/presencefootsteps/config/blockmap.json) which seems to be the main place to assign the different sounds to blocks... I also understand how I would add separate blocks with their own states to this.
The only thing left is to understand how and where I would add this override.

Help of any kind is apreciated.

**Comment by Sollace** [comment]
@Andre601 Instrument is an enum property, so it should be upper case "HARP" not "harp". This is why your resourcepack has not been working no matter the order you load it in.

**Comment by Sollace** [comment]
The new version will treat both versions the same, so this should no longer be an issue. Load order was never a problem, but it will also give entries with attribute contraints priority, so that should solve that issue as well.

**Comment by Andre601** [comment]
> @Andre601 Instrument is an enum property, so it should be upper case "HARP" not "harp". This is why your resourcepack has not been working no matter the order you load it in.

Thank you, that finally solved the issue.
