### ISSUE TITLE
Game crashes when I deleted a world

### ISSUE THREAD

**Issue by vinnyg0621** [Sollace/Presence-Footsteps#109]
the crash report:

https://www.toptal.com/developers/hastebin/raw/sonacohupi

**Comment by vinnyg0621** [comment]
the launcher didn't open back up. the game just closed

**Comment by Sollace** [comment]
What you've attached is not a crash report. It's just a log, or otherwise there is no exception in that log.

You can find the actual crash report in the .minecraft/logs folder

**Comment by Sollace** [comment]
Cannot reproduce.
