### ISSUE TITLE
No Jumping Sounds Are Playing

### ISSUE THREAD

**Issue by BrickDaForceYT** [Sollace/Presence-Footsteps#11]
When playing the game, I noticed there wasn't any sounds when jumping off of a block. There was all the other sounds, walking, landing, running and shuffling. But when I looked through the PF.Resources file, there weren't any sound files for jumping at all. Can you fix that, or is it beyond your capability? Thanks!

**Comment by Sollace** [comment]
I should check, I don't remember it ever being intended to have a jumping sound. Only landing and stepping.

**Comment by Brottweiler** [comment]
@Sollace If I recall correctly, there's a sound for when your feet leave the ground.

**Comment by BrickDaForceYT** [comment]
Yeah, there was a sound for leaving the ground. You can check the video AntVenom did on it, and the official video on the website for Presence Footsteps.

**Comment by BrickDaForceYT** [comment]
Quote from the July 2013 Introduction Video: "...For instance, **jumping** and landing sounds, foot shuffling, walking through materials..."

**Comment by BrickDaForceYT** [comment]
@Sollace I just downloaded the 1.7.10 version, and it does in fact have sounds when you leave the ground. I compared stone sounds. I found that one of the sounds when you leave the ground is the stone_wander1.ogg file.

**Comment by Sollace** [comment]
Alright. I'll look at fixing it.

**Comment by Sollace** [comment]
Question: When testing this which stance do you have it set to (F9)?

Jumping sounds all seem fine, it's only when you have a pegasus stance that it doesn't play sounds under a certain fall distance.

**Comment by BrickDaForceYT** [comment]
I have it set to auto. I see there's Bipedal, should I use that instead? Because I still can't hear sounds when pressing space (rising off the ground)

**Comment by Sollace** [comment]
@BrickDaForceYT 
That's fine. I found the problem.

**Comment by BrickDaForceYT** [comment]
Ok, so hopefully that means it will be fixed. I dunno why, but it just really bugs me that the sounds when leaving the ground aren't there.

**Comment by Sollace** [comment]
It should be fixed now, in both 1.8.9 and 1.9. You can get the updated version from the releases section.

**Comment by BrickDaForceYT** [comment]
Thank you for fixing it, now the mod feels complete again!
