### ISSUE TITLE
Certain blocks are always considered "wet"

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#111]
Some blocks always sound like as if they are wet, despite not being next to or underneath a watersource.

The following video showcases this. The block in question is a retextured Noteblock (Instrument "BIT", note 19) and while it sounds normal at 0:21 does it have the added *wet* sound effect at 0:55.

https://www.youtube.com/watch?v=9Aey3C4dm2I

The blockmap.json I use through a resource pack has `brickstone` set as sound for this particular note block.

The corresponding entry in the resource pack:
https://github.com/Andre601/Presence-Footsteps-x-Origin-Realms/blob/main/OriginRealms-x-Presence-Footsteps/assets/presencefootsteps/config/blockmap.json#L345

For clarity: The blocks are not underneath a water source, nor do they have one right next to or underneath them.

**Comment by Sollace** [comment]
Are there any blocks in that area with the waterlogged state?

Only other reason I would think it would produce mud sounds there is if it thought it was raining on that block.

The relevant line would be here:
https://github.com/Sollace/Presence-Footsteps/blob/698e790b11c7a24a7fe9d9731f3a9552c3bb8d50/src/main/java/eu/ha3/presencefootsteps/world/PFSolver.java#L233

Not sure if it appears in production logs, but can you see if it produces the message "Wet block detected: " in the game logs when this happens?

**Comment by Sollace** [comment]
btw I love those copper golems you have there.

**Comment by Sollace** [comment]
Also can you tell me what blocks are under that floor? There are certain blocks that have the mud sound in their foliage subtrate, that might be producing the sound through the floor.

**Comment by Andre601** [comment]
> Are there any blocks in that area with the waterlogged state?
> 
> Only other reason I would think it would produce mud sounds there is if it thought it was raining on that block.
> 
> The relevant line would be here:
> 
> https://github.com/Sollace/Presence-Footsteps/blob/698e790b11c7a24a7fe9d9731f3a9552c3bb8d50/src/main/java/eu/ha3/presencefootsteps/world/PFSolver.java#L233
> 
> Not sure if it appears in production logs, but can you see if it produces the message "Wet block detected: " in the game logs when this happens?

Nope. The closest water source or waterlogged blocks (In this case waterlogged stonebrick stairs) are like 20+ blocks away and also on different heights.
Also, the latest logs do not have any mention of such a line when checking.

> btw I love those copper golems you have there.

Yeah, they're nice. Part of the server I play on which added all Mobs from that vote to it.

> Also can you tell me what blocks are under that floor? There are certain blocks that have the mud sound in their foliage subtrate, that might be producing the sound through the floor.

I checked, there is mostly stone, cobblestone and dirt, but not really anything else.

**Comment by Sollace** [comment]
@Andre601 Hm... Okay. Is there a way I can get onto that server to test what's happening?

**Comment by Andre601** [comment]
> @Andre601 Hm... Okay. Is there a way I can get onto that server to test what's happening?

The server is public. IP is play.originrealms.com

You would need to craft those blocks yourself tho... Alternatively could I invite you to my realm/world to test out...

**Comment by Sollace** [comment]
@Andre601 Yeah, you can. If I can see the place you showcased in the video myself, it may help.

So far I haven't been able to reproduce your issue in singleplayer at all.

**Comment by Andre601** [comment]
Okay. I'm now on the server, so feel free to contact me there so that you can check it out.
