### ISSUE TITLE
Modloader documentation

### ISSUE THREAD

**Issue by Atlantispy** [Sollace/Presence-Footsteps#114]
Hi, the modpage didn't make it clear that this is fabric only, only noticed once I'd downloaded and installed that it wasn't going to work.

**Comment by Sollace** [comment]
The file is clearly labelled as fabric. There is a separate forge port on curseforge that is not maintained by me, so it may not be updated. 
![image](https://user-images.githubusercontent.com/6429283/145692696-a7345b69-56f7-49d2-ac2e-e51433f45998.png)
