### ISSUE TITLE
Stepping on blocks that have bamboo on them plays the "woodutility" sound

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#117]
When you step on a block that has a bamboo growing on it will the mod play the "woodutility" sound even tho the block is something else (i.e. grass, dirt, etc.)

**Comment by Sollace** [comment]
This is intentional as the bamboo has brush sounds that play when you move through them.

**Comment by Andre601** [comment]
But why does that brush effect sound like as if you step on some squeeky wood?

**Comment by Sollace** [comment]
Baboo is squeaky, it makes that sound when you brush against them 'cause they're bendy and creak a lot. It's the same sound they make when you stand on them.
