### ISSUE TITLE
Some little issues 

### ISSUE THREAD

**Issue by KentaJin** [Sollace/Presence-Footsteps#12]
Some sound such as swimming, climb ladder (and there maybe more) seem to be disappear from user but other player around still make those sound.
Other player make footstep sound and original minecraft block sound kinda annoying

**Comment by Sollace** [comment]
@KentaJin 
I'm... not sure what you're trying to say.

If you have a problem with multiplayer sounds you can turn them off in the settings menu (F9).

**Comment by KentaJin** [comment]
@Sollace 
Its hard to explain.
Let me try my best
 
**• Multiple sound:**
     Mod and vanilla footstep sound both appear on other player when they walk or jump mean it make double sound
 **• Bug?**
     When you climb a ladder or swim you hear no sound, but when other player do you can hear their climbing and swimming sound
 
That's all i will tell, if you still don't understand, i will make a video for you
Also sorry about my grammar is not good

**Comment by Brottweiler** [comment]
>Mod and vanilla footstep sound both appear on other player when they walk or jump mean it make double sound
In the options, enable "multiplayer mode".

>When you climb a ladder or swim you hear no sound, but when other player do you can hear their climbing and swimming sound
Are you using another resource pack? Try to use only PF Resources, and see if it still does not happen. Also make sure you are using the latest PF resource pack.

**Comment by Sollace** [comment]
>  • Multiple sound:
> Mod and vanilla footstep sound both appear on other player when they walk or jump mean it make double sound
Ah, I see.

The server must still be sending sounds for those players, which I have no control over unfortunately. I'll have to dig around to see if I can stop them from playing.

**Comment by KentaJin** [comment]
@Brottweiler i enable multiplayer mode that's why i can hear two sound together, i use a sound pack but put it at bottom i don't think it will effect. 

@Sollace server send no sound to them and i know it, i have a private server to test and those sound still like that 

There is one solution i can do for now is make vanilla footstep sound become mute (blank) 

But hope you guys have solution

**Comment by Brottweiler** [comment]
Just put PF Resources at the top, and try. You haven't even tried it.

**Comment by KentaJin** [comment]
@Brottweiler I'm not a brainless person you can see, of course PF is on top :T

**Comment by Brottweiler** [comment]
@KentaJin Oh sorry, I thought you said you put PF at the bottom, not your other resourcepack!

**Comment by KentaJin** [comment]
@Brottweiler Its okay ^^

**Comment by KentaJin** [comment]
EDIT:
I have test on 1.8.9 ver, the swimming and ladder sound still normal but 1.9.x

**Comment by KentaJin** [comment]
current solution: PF resource pack will add blank sound to replace on all vanilla step sound and its good
-> Bad thing that when you re breaking block its basically mute since minecraft DEV team way too lazy and make setp sound is breaking block sound (mean the sound while you are hitting the block before break it)
