### ISSUE TITLE
Is there a way to add different sounds when wearing armor?

### ISSUE THREAD

**Issue by ScoobyVI** [Sollace/Presence-Footsteps#123]
Hi! This is one of my favorite installed mods, thanks for your work on it!

I was wondering if there was a way I could fiddle with the files to make different sounds play when the player is wearing armor?

I've been using the mAmbience mod alongside this, it has a kind of modular sound play for different pieces of different kinds of armor and wanted to bring those sound files over to work with Presence Footsteps.
At the moment, I've muted all other mAmbience footsteps so just the armor noises overlay the Presence Footsteps sounds - but the walking rhythm doesn't match and it leaves a horse-like pattern 

If creating armor specific sound path isn't possible, is there a way to mute the Presence Footsteps sounds only while armor is worn? That way I could leave the mAmbience armor footsteps as they are 

Thanks a lot

**Comment by Sollace** [comment]
Hi, and welcome!

First off, for the pattern, make sure you have the stance in the mod's settings set to bipedal or auto. It should only be producing a clip-clip pattern 4-legged/quadrupedal model.

Ragarding armor sounds, we don't really have support for that. The mod is primarily focused on producing footsteps based on the blocks you walk on, not on the material of the player's feet, and I was never really interested in turning this into another MatMos mod.

There's also the matter of the extra work and sounds I would have to put in to do different boots.

**Comment by ScoobyVI** [comment]
Thanks for the quick reply!

The pattern is caused by the walking sounds playing on top of mAmbience's armor walking sounds, which has it's own footrsteps play with it too - but not a problem, just wondered if this was something I could do in the settings

Thanks a lot :)
