### ISSUE TITLE
Bug: patterned glasses and panes are registering as wood variants when you walk on them

### ISSUE THREAD

**Issue by EGOIST1372** [Sollace/Presence-Footsteps#129]
in [patterned glass mod](https://www.curseforge.com/minecraft/mc-mods/patterned-glass), patterned glasses and panes are registering as both wood and glass variants when you walk on them base on the sound subtitle(wood creaks)
![image](https://user-images.githubusercontent.com/86555131/154702334-e9bcc81a-1592-4b2e-8242-dbef1ce6a413.png)

**Comment by Sollace** [comment]
I don't assign sounds to modded blocks. It's up to the mod creator or you to make a resourcepack for that.

**Comment by EGOIST1372** [comment]
it was a bug from other mod that got fixed so fast
