### ISSUE TITLE
Presence Footsetps config folder isn't in the Minecraft config folder

### ISSUE THREAD

**Issue by Hypsellis** [Sollace/Presence-Footsteps#13]
The Presence Footsetps config folder doesn't generate it in the Minecraft config folder but directly in the Minecraft folder, wich is pretty annoying. Is it possible to generate in the config folder like all other mods ?

**Comment by Hypsellis** [comment]
I can tell the same thing with Matmos config folder wich generates directly in the mod folder while to be in the config folder.

**Comment by Sollace** [comment]
They both actually used to generate in the mods folder. I changed it in Presence Footsteps a while ago before I got MAtmos.

I have no idea if I'll ever fix this, honestly. Perhaps alongside a 1.10.2 update.

**Comment by Hypsellis** [comment]
PresenceFootsteps and Matmos config still generate them in Minecraft and mods directory and not in config directory. ^^'

**Comment by Sollace** [comment]
Matmos will be updated to put its configs in the same place as Presence Footsteps.
