### ISSUE TITLE
No sound when on the edge of the block

### ISSUE THREAD

**Issue by liabri** [Sollace/Presence-Footsteps#133]
I noticed while doing parkour that if I land on the very edge of a block, there's no sound. To reproduce this easily you can stand on a single block, shift towards the end and just hold space bar. When jumping at any other point on the block a sound is always produced, but there's nothing on the edge of the block.

**Comment by Sollace** [comment]
I can't seem to reproduce this. Does it maybe happen only on certain types of blocks? Stairs and/or fences?

**Comment by liabri** [comment]
Ill have a look on the newer versions but it was happening on every block.
