### ISSUE TITLE
Remastered icon (question)

### ISSUE THREAD

**Issue by xlifi** [Sollace/Presence-Footsteps#134]
### Asking cause i want to make more friendly README.md (you can see in ![my fork](https://github.com/xlifi/Presence-Footsteps)) and i need to know if you would accept it

Old: 
<a><img src="https://user-images.githubusercontent.com/70767436/159658438-b1646691-c25c-4e5c-bbc6-6ee3ea16aa02.png" height="auto" width="150"></a>

New: 
<a><img src="https://user-images.githubusercontent.com/70767436/159660582-0ba3bce9-a353-42e0-af0b-990e24dd99fa.png" height="auto" width="150"></a>

**Comment by Sollace** [comment]
Other than a few changes to the design, I'd say it looks pretty nice. I would still use the original logo for that classic look where the extra resolution isn't needed, though.

The most noticeable thing for me is the perspective on the leg has changed and ground has changed from farmland to dirt.
