### ISSUE TITLE
Balance volume between player and other entities footsteps 

### ISSUE THREAD

**Issue by ThinkWithPbody** [Sollace/Presence-Footsteps#137]
The player's footsteps are much louder than other players/entities close by. Could there be an option to tweak these sounds so that we can have configurations that play them at equal sounds, or disable only player sounds?

**Comment by Sollace** [comment]
Presence Footsteps has a volume slider for this purpose.

**Comment by ThinkWithPbody** [comment]
The current volume slider only controls the overall sound of all entities, and not between the player character and other players/entities. If I were to walk alongside another player, shoulders touching, I would hear my own footsteps much louder than anything else. I'm proposing an option that lets you adjust volumes based on their source, so that it's possible to hear sounds in proportion to how far they are away from you.
