### ISSUE TITLE
Lots of Sound overlappings

### ISSUE THREAD

**Issue by Ayuma-cell** [Sollace/Presence-Footsteps#142]
Hey!
So just wanted to let you know I'm exploring the area a bit in creative and sometimes get multiple instances of the very same sound overlapping each other making it go really loud. I assume it happens if I land on multiple Grass tiles at the same time, but it's kinda hard to replicate tbh.
A way to fix that could be a check if one instance is already playing or not. In the case of needing multiple faster (maybe slightly overlapping) sounds you could add a tiny 0.25 second delay or smth so things don't fire all at once but still repeatably!

**Comment by Sollace** [comment]
Ah yeah, this very likely is from it picking up the same sound from multiple blocks at once. I think I _should_ be able to fix it just by just removing the duplicates. I'll see what I can do.
