### ISSUE TITLE
[Suggestion] Satyr stance (paired bipedal) 

### ISSUE THREAD

**Issue by sisby-folk** [Sollace/Presence-Footsteps#143]
Hey hi there! I've found that the stance system is great for my pack players! but it did occur to me that another stance could be added - notably, a bipedal stance where steps occur in close pairs, similarly to the "clip-clop" gait of satyrs in many representations.

Another thing that might suit origins integration, as well.

**Comment by Sollace** [comment]
We do already have a quadrupedal stance, which has that clip-clop gait to emulate the way horses walk. Is that maybe what you're looking for?

**Comment by Sollace** [comment]
Closing, as I've had no response in 7 days.

**Comment by sisby-folk** [comment]
Oops! got busy for a while. 

The quadrupedal stance is really nice! While sprinting across, say, wood planks, there's a very distinct galloping "four" pattern that repeats. This suggestion was in interest in the idea of using the same sounds in pairs of two instead.

**Comment by sisby-folk** [comment]
To vaguely lay it out in text, the quadrupedal gallop pattern looks something like `1234--1234--1234--`, and bipedal looks something like `1-2-1-2-1-2-1-2`. A "satyr" (or any bipedal animal with the same kind of leg structure) might have a gait with the same clop-ish noises of quadrupedal, but in the pattern `12-12-12-12-12`
