### ISSUE TITLE
Crash in Deathduskmodpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [Sollace/Presence-Footsteps#144]
What happened?
Found a End City, entered it and my game crashed now when i try to log in again it always crash...welp

Provide the log
https://bytebin.lucko.me/bhQrUuiQGR

**Comment by macmawhiney** [comment]
I have the same problem...

**Comment by Sollace** [comment]
Ah, so sorry! I had worked on this but forgot to push it.

**Comment by Sollace** [comment]
Duplicate of #135

**Comment by TheButterbrotMan** [comment]
When you will push the new version?

**Comment by TheButterbrotMan** [comment]
@Sollace When you will push the new version?

**Comment by Sollace** [comment]
@TheButterbrotMan The fix has already been released. Update to 1.19.
