### ISSUE TITLE
walking on stone sounds too wet

### ISSUE THREAD

**Issue by asheden** [Sollace/Presence-Footsteps#148]
whenever the player walks on stone, it has a texture that sounds almost way too wet, almost as if it were meant to play when it's raining. the high frequencies sound like they shouldn't even be there, like the player is walking on gravel, rather than stone

**Comment by Sollace** [comment]
Closing this, as this is something you can change with a resource pack. https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators
