### ISSUE TITLE
No 1.19 Version Yet

### ISSUE THREAD

**Issue by NotArchiTron** [Sollace/Presence-Footsteps#150]
Do I have to describe? ( Their is just no 1.19 Version yet )

**Comment by Jevkray** [comment]
Im waiting <_<

**Comment by FabulatorK** [comment]
For some reason, with this mod enabled on 1.19 (I know I am forcing it), the game would be stuck in an infinite loading screen and render the starting menu inaccessible.

**Comment by Jevkray** [comment]
me too # @FabulatorK
