### ISSUE TITLE
Default soundpack is being shipped...or is it?

### ISSUE THREAD

**Issue by Namnodorel** [Sollace/Presence-Footsteps#16]
Apparently, it is not. When joining a world, I get the message

<PF> Resource Pack missing from resourcepacks/!
You may have forgotten to put the resourcepack in your resourcepacks/ folder.

After some searching I did not find any resourcepack I could've forgotten. What should I do about this? No footsteps are played at all.

**Comment by Sollace** [comment]
There should be a resource pack you can download alongside the mod. You need to have it installed and enabled before the mod will work.

**Comment by Namnodorel** [comment]
But where? I was unable to find anything...

**Comment by Sollace** [comment]
Which version are you looking for?

A resourcepack should be linked alongside the download for [each one.](https://github.com/Sollace/Presence-Footsteps/releases)

**Comment by Namnodorel** [comment]
The latest. And, uuhm... Yeah, there's a resource pack link... Sorry, I confused it with the sources-zip
