### ISSUE TITLE
Feature Request: Guessing the material for a superficial mod compatibility

### ISSUE THREAD

**Issue by Grumpey102** [Sollace/Presence-Footsteps#164]
Hey,

I'd really like to use the mod, but too many modded blocks don't have a sound and it's a lot of work to manually check which blocks make a sound and which don't, and to add a sound, if they don't have any.

For example: The Blockus mod for fabric doesn't have sounds for any walls or for any amethyst block, and many more blocks also don't have a sound.

I don't speak minecraft programming language, but I'd wonder if you could add a function which:

1) Checks, if a mod has a custom sound resource pack
2) If not reads the names of the added blocks
3) Compares the name with a **prioritized** list of keywords from high priority to low priority.
4) Adds the sound to the block with a matching keyword.
5) Lets users define new keywords to check for (resource pack, ingame menu, etc.)

For example:
Your mod would go through the blockus mod and see blockus:stone_tiles, so it would be logical for it to have a stone sound. It would see andesite_brick_wall and it should have an andesite or brick sound.

It could be difficult for things like blockus:snow_bricks, because if it would get a "bricks" sound, it would probably sound weird. That's where the priorization of the keywords would come in handy. "Snow" would have a higher priority than "bricks", so it would take the "snow" sounds.

Of course that would still leave room for error, like if some modder decides to add blocks that have hard-coded snow in the texture and calls it "snowy_bricks", but then a user could just add a "snowy", put it somewhere around the other "snow" keyword and be done with it, because *all* of the "snowy" bricks, planks, walls, etc. would immediately have a sound.

Cheers,
Grumpey

**Comment by Sollace** [comment]
The mod already attempts to guess the correct material based on the sound the block makes. If it's using any of the vanilla sounds, it uses the primitive map to detremine the sound to play for it. If the mod uses its own sounds, though, there's nothing to go on.

I agree it shouldn't be making _no sound at all_, which is something I've noticed before, so I'll definitely look into this and maybe improving mod compatibility further. Don't expect it to be a perfect solution though. There's a reason why this mod is built in a way everything it does can be configured by a resource pack.

Also I encourage modders to provided configs for Presence Footsteps as part of their mods too, if that's something they're interested in. If they can do that, it would make the overall experience for all of us a lot better.

**Comment by Grumpey102** [comment]
Right,

if you want to look into it, I specifically mean the [blockus mod](https://www.curseforge.com/minecraft/mc-mods/blockus) and it's loads and loads of blocks not working from that mod. In this screenshot you see a few of the blocks not making any sound at all. Tuff blocks, Amethyst blocks, etc. I tried finding out which blocks don't make a sound in order to create the plugin file you mentioned myself and maybe upload it on curseforge but after a few hours of work I was overwhelmed with the task. I don't know if the creator of blockus has better resources than me, but for me it was too much.

![grafik](https://user-images.githubusercontent.com/110056966/185784257-829bcbf9-e965-4c48-ad00-a54ba7bfdb95.png)

Anyway, thanks for the reply :)

**Comment by Sollace** [comment]
Ah, thanks. Looks like they're all blocks using newer materials. I may have forgotten to set up mapping for those materials, so that may explain the issue.

I'll sort it out when I'm do the next 1.19.2 release.

**Comment by Sollace** [comment]
To help with debugging, you can look on the F3 screen for what materials Presence Footsteps maps for the block you're looking at.
