### ISSUE TITLE
1.10.2 version?

### ISSUE THREAD

**Issue by Namnodorel** [Sollace/Presence-Footsteps#17]
Using the latest stable version of both liteloader and forge, PF is not loaded and doesn't do anything. I tried updating the version number in litemod.json; after that the mod was loaded but didn't do anything.

**Comment by Brottweiler** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound?comment=667

**Comment by Namnodorel** [comment]
Not working.

**Comment by Brottweiler** [comment]
@Namnodorel Alternativly you can edit the json file in the `.litemod` archive and change `1.10` to `1.10.2` I think.

**Comment by Namnodorel** [comment]
Did you...did you read what I wrote in the original issue?

**Comment by Brottweiler** [comment]
Sorry, I had to have missed it. There's no reason it would not work, though, since it has worked for me. Would you show how the json file looks like?

**Comment by Namnodorel** [comment]
`{
    "name": "eu.ha3.presencefootsteps",
    "mcversion": "1.10.2",
    "version": "u11",
    "revision": "1",
    "author": "Hurricaaane (Ha3)",
    "url": "http://presencefootsteps.ha3.eu",
    "description": "An overly complicated sound mod",
    "mixinConfigs": [
        "mixins.presencefootsteps.json"
    ]
}
`

**Comment by Brottweiler** [comment]
This is exactly what I am using, and it works.

```json
{
    "name": "eu.ha3.presencefootsteps",
    "mcversion": "1.10.r1",
    "version": "u11",
    "revision": "1",
    "author": "Hurricaaane (Ha3)",
    "url": "http://presencefootsteps.ha3.eu",
    "description": "An overly complicated sound mod",
    "mixinConfigs": [
        "mixins.presencefootsteps.json"
    ]
}
```

Using `r1` is recommended by Mumfrey, this way it will work in both `1.10` and `1.10.2` actually.

**Comment by Namnodorel** [comment]
Still not working...
