### ISSUE TITLE
Presence Footsteps not working with weathering/rusting iron from any mods

### ISSUE THREAD

**Issue by FluffyBumblebees** [Sollace/Presence-Footsteps#170]
Rusted Iron
Charm

^ mods that I know don't work.

**Comment by Sollace** [comment]
I don't provide sounds for other mods. If they're using a custom material/step sound that's not part of vanilla either they have to add presence footsteps support to their mod by including a blockmap.json or you have to add it with a resource pack.

**Comment by FluffyBumblebees** [comment]
They use the same sounds... Hmmm I'll report it to them then

**Comment by Sollace** [comment]
If so, try with the version I released today, because I fixed primitive mappings for a lot of vanilla sounds.

**Comment by FluffyBumblebees** [comment]
ok

**Comment by FluffyBumblebees** [comment]
Issue persists. Issue for charm
