### ISSUE TITLE
Presence Footsteps 1.5.1 crashes on Minecraft 1.18.1

### ISSUE THREAD

**Issue by Ruchian** [Sollace/Presence-Footsteps#174]
Presence Footsteps version 1.5.1 doesn't work on Minecraft 1.18.1.

Installing the mod (version 1.5.1) , together with Fabric 0.14.9 , Fabric-API 0.46.6 boots up the game, but problems occur when you load up a world.

To test, you can create a flat world with preset Redstone Ready for example, then load up the world. The result is a crash with a "No Class Def Found Exception"
(report here: https://paste.ee/p/CfxVM )

I tried various mod combinations to see if I can make it work, but alas. I don't know if it is missing something.

Currently the only workaround is rolling back to Presence Footsteps version 1.4.0

**Comment by Sollace** [comment]
You need to use 1.18.2. Seems like there are breaking changes between the two that prevents the mod from working on the older version.
