### ISSUE TITLE
HRTF directional audio grass sounds incorrect and offset.

### ISSUE THREAD

**Issue by jacklollz2** [Sollace/Presence-Footsteps#175]
When enabling HRTF, the grass step sound partially comes from the right and does not sound correct.
Other step sounds like gravel and sand do not have this issue, or is too minute to notice.

**Comment by Sollace** [comment]
What's HRTF?

**Comment by jacklollz2** [comment]
> What's HRTF?

1.19 has HRTF in the settings. Music/Sound > Directional Audio.

**Comment by Sollace** [comment]
I've never seen that option, but I guess I will check.

**Comment by Sollace** [comment]
Closing as I can't hear anything wrong with directional audio enabled.
