### ISSUE TITLE
Dark Oak Log + Stripped Dark Oak Log + Stripped Dark Oak Wood habe different step sound than other logs

### ISSUE THREAD

**Issue by xXNickznXx** [Sollace/Presence-Footsteps#177]
Using: PresenceFootsteps-1.5.1.jar
I don't know if it's intentional, but these 3 blocks have different step sounds. Appears to be the fence step sound.

And Dark Oak WOOD, yes wood not log, has the normal log step sound.

**Comment by Sollace** [comment]
This is intentional. Dark oak all have distinct sounds.

**Comment by xXNickznXx** [comment]
What about my 2nd point: Dark Oak Wood doesn't have the distinct sound.
