### ISSUE TITLE
Please add compatibility with smallships mod

### ISSUE THREAD

**Issue by Psychodeus** [Sollace/Presence-Footsteps#180]
Please add the sailing part more enjoyable experience, steps on the ship, wind perhaps, and the ocean water touching with the ship mouth. Thank youuuu

[Smallships](https://www.curseforge.com/minecraft/mc-mods/small-ships)

**Comment by Sollace** [comment]
I don't handle mod support. That's something anyone can easily do themself with a resourcepack. https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators

**Comment by Psychodeus** [comment]
OMG alright, this will be my first resource pack then.
