### ISSUE TITLE
Modded ice sounds like glass

### ISSUE THREAD

**Issue by NoobiusMcGuffin** [Sollace/Presence-Footsteps#183]
Any type of modded type of ice added into the game will sound like stepping on glass. If there was a way for you to either fix that or at least make it so we can change the sounds of blocks, that would be great.

**Comment by Sollace** [comment]
You can change the sounds with a resourcepack. https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators

I'll still check the material mapping for ice. If they're using the same material type as vanilla ice blocks, it should already assign them the correct sounds.

**Comment by Sollace** [comment]
Ice in vanilla uses the same step sounds as glass. They can make them sound like ice when Presence Footsteps is installed by adding their blocks to the #minecraft:ice block tag, or by providing a blockmap.json containing the assigned sounds to use for their blocks.

Nothing else I can do unfortunately.
