### ISSUE TITLE
Snow sounds issue

### ISSUE THREAD

**Issue by WiredSamurai** [Sollace/Presence-Footsteps#184]
When walking on top of snow covered blocks, it plays the sound for the block beneath it. Is there any way to fix this issue?

**Comment by Sollace** [comment]
Yep, sounds like a similar problem to carpets. It should be easy to sort out.

**Comment by WiredSamurai** [comment]
Cool, appreciate your awesome work! No rush <3

**Comment by Sollace** [comment]
Can't seem to find the issue here. I assume it must be fixed in dev.
