### ISSUE TITLE
A serious bug on minecraft 1.19.3

### ISSUE THREAD

**Issue by a1544676809** [Sollace/Presence-Footsteps#187]
I don't know how to describe it (my english is poor). this is video of my problem.in this video i used PresenceFootsteps-1.6.1.later i tried PresenceFootsteps-1.6.3,but it has same problem, too. i wish the bug could be fixed, please

https://user-images.githubusercontent.com/85007951/206701395-1386e206-baaa-481f-b396-8d1bcb13188e.mp4

**Comment by Sollace** [comment]
The mod has not been updated to 1.19.3
