### ISSUE TITLE
Presence footsteps

### ISSUE THREAD

**Issue by BitBork** [Sollace/Presence-Footsteps#19]
Hi there Sollace

This isn't really an issue, more kind of a request, and I couldn't seem to find a way to private message you so I'm posting here.
I wanted to ask if you could update your 'presence footsteps' litemod & rcp to 1.12.2. I know this is probably a lot to ask, and you also have life to deal with, but I would be very grateful if you could.

Thanks
BB.

**Comment by Sollace** [comment]
@BitBork Sorry, I don't really maintain these mods any more. The last I'd seen there was someone creating update versions over on the Minecraftforums topic, though. I'd recommend checking there.
