### ISSUE TITLE
Request: Compatibility with Pehkui

### ISSUE THREAD

**Issue by lbplay29** [Sollace/Presence-Footsteps#191]
When you change your size in any way and try to move, the game crashes.
I really don't know anything about coding, so this might be impossible, but if it is, I think it would be a really good addition.

**Comment by Sollace** [comment]
I'm not sure what pehkui does that would cause it to crash. Can you send the crashreport?

**Comment by Aetherloss** [comment]
Hey, I believe I'm also experiencing a crash due to an incompatibility between Pehkui and Presence, I've attached the crash report :)
[crash-2022-12-22_17.30.40-client.txt](https://github.com/Sollace/Presence-Footsteps/files/10284407/crash-2022-12-22_17.30.40-client.txt)

**Comment by Sollace** [comment]
@Aetherloss I think you need to report this to Pehkui. Seems to be a bug on their end because they should never assume the player has a vehicle. I assume it's the same problem @lbplay29 had.

**Comment by Sollace** [comment]
Should be fixed in 1.6.4 (for 1.19.2) and 1.7.1 (for 1.19.3)
