### ISSUE TITLE
Create's on-contraption step sounds are silenced

### ISSUE THREAD

**Issue by TropheusJ** [Sollace/Presence-Footsteps#192]
Presence Footsteps cancels step sounds [here](https://github.com/Sollace/Presence-Footsteps/blob/cef692eee2ed9c2a32d8dd741c5d84bd43f80d46/src/main/java/eu/ha3/presencefootsteps/sound/SoundEngine.java#L158), and replaces them with it's own system. However, this system does not work on Create's contraptions, where stepping is controlled [here](https://github.com/Fabricators-of-Create/Create/blob/5f736588721dbf154312e8ee48fbfea3cdc5cad5/src/main/java/com/simibubi/create/foundation/mixin/EntityContraptionInteractionMixin.java#L91), and so they are not replaced.

**Comment by TropheusJ** [comment]
original issue: https://github.com/Fabricators-of-Create/Create/issues/394

**Comment by Sollace** [comment]
We generate replacement step sounds from the block's material sound (from `Block#getSoundGroup()`) if there isn't an explicit mapping for it, but can currently only recognise sound that are part of the base game.

I may look at adding an additional fallback to using the sound as it's provided if nothing else gives us a mapping, as I've been trying to sort out silent modded blocks for a few versions.

If you want to fix the issue *now* though (and I recommend you do this anyway as the overall result would be better), you should be shipping either a blockmap or a primitivemap as part of your resources to indicate to PR what sounds your blocks are supposed to make and how.

**Comment by TropheusJ** [comment]
missing block sounds is only part of the issue, and in my testing no longer happens. The problem is step sounds on contraptions.

**Comment by Sollace** [comment]
For a few things:
1. Create has not updated past 1.19.2 so I cannot do anything to support it from my end until they can get onto current Minecraft versions.
2. After looking into it, it seems like contraptions are... entities? In that case you or the create devs can just add a [Golem Map](https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators) with the intended material types PresenceFootsteps is supposed to make for them.

Golem Map is like the Block Map, but for entities. It's already used to create footsteps when walking on shulkers and armor stands and should work here too.

I can't say what the intended sound are, but something like this would probably do it:
```
{
   "create:stationary_contraption": "stone",
   "create:gantry_contraption": "stone",
   "create:carriage_contraption": "stone",
   "create:seat": "wood"
}
```

**Comment by Sollace** [comment]
Closing as this is not something I can fix from my side. Even with the [cancelling function mentioned](https://github.com/Sollace/Presence-Footsteps/blob/cef692eee2ed9c2a32d8dd741c5d84bd43f80d46/src/main/java/eu/ha3/presencefootsteps/sound/SoundEngine.java#L158) turned off (via setting the global pf volume to 0)
