### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Looodon** [Sollace/Presence-Footsteps#193]
Hey,
My game crashed and I couldn't get into my world anymore cuz it kept crashing until I removed the mod. Any thoughts as to why?

Crash Log: 
https://paste.gg/p/anonymous/e7d63fede6f740efbc3d4d9d1e170e90

**Comment by Sollace** [comment]
Depending on the minecraft version, you either need to install this version:
https://github.com/Sollace/Presence-Footsteps/releases/tag/1.6.4
Or this one:
https://github.com/Sollace/Presence-Footsteps/releases/tag/1.7.1
