### ISSUE TITLE
[1.18.2]Crash randomly when teleport to players 

### ISSUE THREAD

**Issue by 5ur3z** [Sollace/Presence-Footsteps#195]
As the title said, it will crash when I try to teleport to other players.

[latest.log](https://github.com/Sollace/Presence-Footsteps/files/10401751/latest.log)
[hs_err_pid34680.log](https://github.com/Sollace/Presence-Footsteps/files/10401753/hs_err_pid34680.log)

**Comment by Sollace** [comment]
Looks like a shader crash. You may want to report it to Iris (I can see them in the stack trace).

**Comment by 5ur3z** [comment]
ok thanks, maybe I've solved this problem by upgrade my server from 1.18.2 to 1.19.2
