### ISSUE TITLE
Suggestion: Better sound for grass/moss blocks

### ISSUE THREAD

**Issue by Reber01Good** [Sollace/Presence-Footsteps#198]
I really like what this mod did with all of the sound design, but I think the grass and moss blocks fall behind. The sound does not feel as "grassy" as it should. If you imagine these sounds were recorded with a microphone, unlike the rest of them, the grass block sounds feel like they were recorded form underground. The bass of the sound is way too pronounced, considering you are walking on soft blocks. I think vanilla minecraft did a better job here, since the sound feels like what the in game player would hear in their ears. I hope you understood my complicated explanation.

**Comment by Sollace** [comment]
I somewhat agree. I get what Ha3 was doing with the sounds, but they always sounded more like walking on solid earth than through grass.

I'm not sure when I'll be able to figure out a better sound, but this will be on my mind.

**Comment by Reber01Good** [comment]
Thanks for considering!

**Comment by Reber01Good** [comment]
![Screenshot_1](https://github.com/Sollace/Presence-Footsteps/assets/93145739/303376ac-d2d7-45d3-94cb-5cdfb5f08be8)
I tested the new sounds and they are perfect! Well done! This made my experience with the mod so much better!

**Comment by Sollace** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/93145739/278135700-303376ac-d2d7-45d3-94cb-5cdfb5f08be8.png) I tested the new sounds and they are perfect! Well done! This made my experience with the mod so much better!

I'm glad you like them.
