### ISSUE TITLE
Traverse & Terrestria

### ISSUE THREAD

**Issue by Swordee** [Sollace/Presence-Footsteps#20]
Not an issue, but I'm not sure how to submit a request on GitHub. Sorry about that!
But either way, I'm here to suggest that you add support for Traverse specifically, but also its similar mod, Terrestria. They're are biome mods for Fabric that are increasing in popularity quite quickly. I would imagine Traverse would be quite easy as you would only need to duplicate the sounds for wood and leaves, but Terrestria could be slightly more challenging. However, I'm not a mod developer in anyway, so I wouldn't really know.

If you take this into consideration, thank you :) very nice mod you got here.

**Comment by Sollace** [comment]
Adding support for both those mods should be pretty easy for you or anyone to do on their own. You just need to make a resourcepack to add onto the blockmap.json. ^-^

**Comment by Swordee** [comment]
> Adding support for both those mods should be pretty easy for you or anyone to do on their own. You just need to make a resourcepack to add onto the blockmap.json. ^-^

I will try that, thank you!

**Comment by Sollace** [comment]
@Swordee 
Alrighty! I'm going to be working on a wiki here to make it easier for people to do. If you have any questions, I'll always be here to help.

**Comment by Swordee** [comment]
![image](https://user-images.githubusercontent.com/52900125/62841473-10746a00-bc6e-11e9-83a6-b6c4ceb5bdc7.png)
So, I opened the .jar file for the mod and opened the blockpack.json file. It looks quite simple, so theoretically I would just have to add `"traverse:fir_log": "wood",`

**Comment by Swordee** [comment]
Update: yes that did indeed work!

**Comment by Sollace** [comment]
> Not really sure what you mean by making a resourcepack.
What I means is you can create a blockmap.json and add it to a zip in your resourcepacks folder instead of editing the mod's jar.

It works exactly the same way as you might change textures in the game.
