### ISSUE TITLE
Mod not playing any footstep sounds (Except for wood?) after updating to 1.8.1

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#216]
After updating to 1.8.1 for 1.19.4 (Using Quilt Loader and Quilt Fabric standard libs) have sounds stopped playing at all for me.

The only times I was able to hear anything was when I walked on some wooden slabs, but then was it a very low sound.

Full report created by the mod: https://paste.helpch.at/fogabofodu.pl

Also, on an unrelated note is the message for the generated report having a broken String.format output:
![grafik](https://github.com/Sollace/Presence-Footsteps/assets/11576465/f0d0b920-b9e3-4203-ad66-8cdaf1d3b390)

I want to mention that I do use a resource pack, my own, that applies sound overrides for the mod to make it work with a server I'm playing on. This resource pack worked fine with 1.8.0.
It only contains the blockmap.json to override the sounds. Here's the full file content: https://paste.helpch.at/ivibupovah.json

If needed will I provide a video showcasing the issue.

**Comment by BaconWeeny** [comment]
What you have to do is make it 1.8.0 Ik you just updated it but it worked for me with the same problem

**Comment by Andre601** [comment]
> What you have to do is make it 1.8.0 Ik you just updated it but it worked for me with the same problem

...What?

I know that I can downgrade to avoid this fix... Doesn't solve it tho as 1.8.1 is still present on the mod page(s). So your comment is kinda nonsensical.

**Comment by BaconWeeny** [comment]
I'm using feather client matey! maybe you should check it out, and also no need to call me nonsensical I was just trying to help yah out argghhh!

**Comment by brycerobertson** [comment]
Can confirm this issue as well, loaded into fresh new instance with quilt & fabric and just presence installed, only footstep audio was from wooden slabs nothing else

**Comment by Sollace** [comment]
Fixed! Sorry about that

https://github.com/Sollace/Presence-Footsteps/releases/tag/1.8.2
