### ISSUE TITLE
[Compatability] Presence Footsteps dont work on Valkyrien Skies ships

### ISSUE THREAD

**Issue by milkev** [Sollace/Presence-Footsteps#224]
when walking on an airship from [Valkyrien Skies](https://modrinth.com/mod/valkyrien-skies) the Presence Footsteps are no longer heard.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/322

**Comment by Sollace** [comment]
This sounds similar to the issue with Create #192 (i.e. walking on entities isn't supported)
