### ISSUE TITLE
Sounds while sneaking

### ISSUE THREAD

**Issue by TeRacksito** [Sollace/Presence-Footsteps#226]
In vanilla, you don't make any noise while sneaking/shifting. But with the mod enabled, you can hear sounds while shifting + jumping and also shifting + going down on half blocks like stairs.

I'm pretty sure this is a bug because if a player is coming on my back shifting with the purpose of me not seeing him, this mod will reveal him.

**Comment by Sollace** [comment]
I'm pretty sure step sounds still play in vanilla even when you're sneaking, so this isn't a bug.

**Comment by TeRacksito** [comment]
Hello!

Thanks for answering. I can record a video for you of various situations if you want. On vanilla, while shifting it will never make a sound, not including fall damage.

**Comment by TeRacksito** [comment]
https://github.com/Sollace/Presence-Footsteps/assets/89692861/0e0abd21-54d6-4a53-a265-736ba1e4117c

Here you can see the vanilla behavior. (I edited the bitrate of the video so it can be 10mb or lower to be able to send it)
I activated the vanilla subtitles, so you don't have to even actually listen to the video.

**Comment by TeRacksito** [comment]
https://github.com/Sollace/Presence-Footsteps/assets/89692861/12e39144-1c90-43de-b204-4613ac675c1a

Here you can see the Presence Footsteps mod behavior.
Again, the subtitles are enabled.

**Comment by TeRacksito** [comment]
Watching these videos, it is now clear that this is a bug. You can even see how at the start of the mod's video it makes a sound at the start of the stairs.

**Comment by TeRacksito** [comment]
Also I cannot understand why did you close it.

**Comment by Sollace** [comment]
Alright, reopening it. Sorry about that.

Didn't know sneaking was supposed to have that effect.

**Comment by TeRacksito** [comment]
Don't really worry. We all make mistakes and above all, when one plays with mods, it is very easy to forget how vanilla works.
