### ISSUE TITLE
Featrue request: different sounds for different boots, improve barefoot

### ISSUE THREAD

**Issue by vgrynch** [Sollace/Presence-Footsteps#228]
Hi!
This is a great mod! (Using 1.19.2)

However, there is still a lot of space for improvement:
- It would be good when wearing iron boots produces metal sounds on stone block types. 
- Wearing leather boots probably should make sounds softer. 
- Why do barefoot walking produce sounds on stone like I'm having hooves or shoes? It should not produce sound at all, as per a human walking barefoot on the stone. It's a game about survival in nature, not auto-granting players some invisible shoes :)
- A config to provide custom sounds as files would be great. This is a client-side mod, far not all users know how to define data packs.

**Comment by Sollace** [comment]
> A config to provide custom sounds as files would be great. This is a client-side mod, far not all users know how to define data packs.
Resource packs, not datapacks. You don't need a datapack to change the sounds presence footsteps produces just like you don't need it for changing any of the sounds in vanilla.

**Comment by vgrynch** [comment]
Any way to update 1.19.2 version with the new features? 1.19.2 is still very popular because of the vast amount of very good mods for that version.
