### ISSUE TITLE
is this a client sided mod?

### ISSUE THREAD

**Issue by Nathan22211** [Sollace/Presence-Footsteps#23]
i know i shouldn't be using the issue tracker for this reason but it's unclear to me if it is a client sided mod or not

**Comment by Sollace** [comment]
Yes, it's completely a client-side mod. I won't do anything if you install it on the server (in fact I discourage anyone from installing it on a server)

Also, because it's client side, you will be able to play on any modded/unmodded server and still be able to enjoy your better-sounding feet. :)

**Comment by netcore10** [comment]
Will this also be updated for forge? It would be nice to use this in official modpacks.

**Comment by Sollace** [comment]
No. This is a fabric mod.
