### ISSUE TITLE
Mod plays sound of unpowered note block despite block being powered and having separate sound assigned...

### ISSUE THREAD

**Issue by Andre601** [Sollace/Presence-Footsteps#230]
I currently encounter a rather strange issue where the Presence Footsteps mod seems to play the wrong sound for a block... But only for certain blocks it seems...

I've double and tripple checked the blockmap.json I made and the JSON format is right and the block entry matches the one on the world itself.
I also made sure the resource pack is at the very top to not be overriden by any other one that could have blockmap.json files (Although to my knowledge do none of the others have any PF compat built-in).

Here is the blockmap.json in question: https://paste.helpch.at/bafofufisa.json

Here is a truncated list of entries I found having issues. There are way more than that...

- `"note_block[instrument=BASEDRUM,note=1,powered=true]": "chimes"` (Plays wood)
- `"note_block[instrument=BASEDRUM,note=3,powered=true]": "bone"` (Plays stone)
- `"note_block[instrument=BASEDRUM,note=9,powered=true]": "organic_solid"` (Plays stone)
- `"note_block[instrument=BASEDRUM,note=13,powered=true]": "wood"` (Plays wood,mushroom)
- `"note_block[instrument=BASEDRUM,note=17,powered=true]": "wood"` (Plays wood,mushroom)
- `"note_block[instrument=BASEDRUM,note=18,powered=true]": "marble"` (Plays wood,mushroom)

As you may notice, all these have in common that they play the sound defined for the unpowered counterpart.
Other powered note blocks do play as they should (At least some do. Others may coincidentally have the same sound assigned so it's not noticable).

I also tried changing the order to have the unpowered ones above the powered ones but no difference here...

I'm at a complete loss here as to why this happens.
I did make a world for debugging where I have larger areas of note blocks to walk over to test this out. And looking at it through the debug-screen shows the note blocks having the right assigned instruments and being `powered: true` state, so unless the debug screen is for some reason getting wrong data, can we assume the blocks to be in their right state here.

I also wanted to create a report, but received this error in the process:
```
Failed to generate report: Unknown namespace: named (we know about [official, intermediary])
```
I have no idea what it means and/or if it is related to the issue I have right now.

**Comment by Sollace** [comment]
I suspict it could be related to one of the changes in https://github.com/Sollace/Presence-Footsteps/commit/8dc355340ce181d91d0829c211c569d2cbaae029

Could you try with this version and let me know if it's any better?

https://github.com/Sollace/Presence-Footsteps/releases/download/1.9.1-beta.1/PresenceFootsteps-1.9.1-beta.1.jar

**Comment by Andre601** [comment]
This seems to have fixed it indeed.

Tho, to be honest did it at first not work, but after updating some other values and making a new Zip file to load did it work...

**Comment by Sollace** [comment]
Hm alright. Seems the load order was wrong in the mod anyway. Thanks for confirming that it worked.
