### ISSUE TITLE
Husk walking sound is bugged

### ISSUE THREAD

**Issue by CAPTAIN-Ilay** [Sollace/Presence-Footsteps#235]
Basically, if there's a husk walking nearby, you will hear his footsteps as if it was right next to you no matter what the distance is.
If you use the option to disable the sound of footsteps from hostile mobs, it will work for every respective mob except husk.

Version: 1.20

I can provide footage if it's needed.

**Comment by Sollace** [comment]
Cannot reproduce with directional sounds on or off. Husk foosteps originate from where they're standing, not the player.
