### ISSUE TITLE
[Compatibility] Presence footsteps causes crashes when sitting in seats from "Just Outdoor Stuffs" with Mine Little Pony

### ISSUE THREAD

**Issue by IDeletedSystem64** [Sollace/Presence-Footsteps#238]
When sitting in the Patio sofa pieces, the game crashes and will crash on server or world join until the mod is disabled so the player can leave the seat

Crash reports:
https://pastebin.com/xHq26h5j
https://pastebin.com/nSSdUCFP

**Comment by Sollace** [comment]
Looks like that mod is not providing textures for its entities (this should never happen!).

I'm going to fix the crash, but I've also filed a bug report with the mod since it will likely cause issues for other mods as well if they ever end up interacting.
