### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Neogamer789** [Sollace/Presence-Footsteps#24]
Hello the mod is crashing at startup, do you have any solution ?

Here's my log : 

> Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> [02:24:09] [main/INFO]: Loading for game Minecraft 1.14.4
> Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
> 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: presencefootsteps requires {fabric-api-base @ [>=0.1.0]})
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
> 	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
> 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
> 	... 2 more
> Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
> 	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
> 	... 4 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (17 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1

**Comment by Sollace** [comment]
You have to download fabric-api and put it in your mods folder.
