### ISSUE TITLE
Embedded URL does not work

### ISSUE THREAD

**Issue by Abbanon** [Sollace/Presence-Footsteps#240]
The embedded mod URL (http://presencefootsteps.ha3.eu/) doesn't work.
Maybe it should redirect to this GitHub repo instead? Or the CurseForge/Modrinth pages?
_What the link currently directs to:_
![Screenshot_1](https://github.com/Sollace/Presence-Footsteps/assets/37251822/6f3fce6e-a11a-4512-810c-5069bea07b60)

**Comment by Sollace** [comment]
I unfortunately don't have control of that domain. It belonged to @Hurricaaane who is currently inactive.

I will see about replacing it with modrinth when I have the opportunity.
