### ISSUE TITLE
No Sounds of Footstep

### ISSUE THREAD

**Issue by Thelegendking** [Sollace/Presence-Footsteps#244]
There is no sound of footstep after updating from 1.9.0 to 1.9.1 for minecraft 1.20.1 fabric.

**Comment by Sollace** [comment]
Check your resource packs and make sure the built in pack is enabled.

**Comment by Thelegendking** [comment]
After adding it to selected list its working now thanks but now the problem is but a minor one that I set up my mod's setting to only for "Player+Hostile" but its making footsteps from all mobs.
