### ISSUE TITLE
Audio sounds hollow

### ISSUE THREAD

**Issue by MissPotato** [Sollace/Presence-Footsteps#25]
All sounds seem to have a small reverb making it sound like the blocks are actually hollow. I've mitigated this by changing the f10 volume down to 1/10th, but at that point, it defeats the purpose of the mod.

**Comment by Sollace** [comment]
I don't hear what you're describing when I play, and changing the sounds isn't exactly an easy thing to do.

A lot of the wooden blocks are also intended to sound hollow. If you've ever walked on a wooden floor or balcony that's pretty much exactly the type of sound you can expect to hear.
