### ISSUE TITLE
Crashes the game on startup

### ISSUE THREAD

**Issue by Chris6ix** [Sollace/Presence-Footsteps#250]
Presence Footsteps just crashes the game on startup.
Because the error doesn't mention what mod caused it, I had to remove mods until it didn't crash anymore, and as soon as I removed Presence Footsteps the game started fine.
Here is the crash log:
[crash-2023-11-19_16.03.37-client.txt](https://github.com/Sollace/Presence-Footsteps/files/13403614/crash-2023-11-19_16.03.37-client.txt)

**Comment by Sollace** [comment]
You're using the wrong version. For 1.20.2 you need [1.10.0](https://github.com/Sollace/Presence-Footsteps/releases/tag/1.10.0)

**Comment by Chris6ix** [comment]
Oh alright, thanks. That version is not available on Curseforge though. I just tried the latest version that was there, because I have some other mods that work on 1.20.2 despite only showing as 1.20.1 compatible :)

**Comment by Sollace** [comment]
> Oh alright, thanks. That version is not available on Curseforge though. I just tried the latest version that was there, because I have some other mods that work on 1.20.2 despite only showing as 1.20.1 compatible :)

The curseforge page isn't receiving updates. I recommend using [the modrinth page instead](https://modrinth.com/mod/presence-footsteps) as that is receiving the most recent updates.
