### ISSUE TITLE
Seperate Audio Setting Slider?

### ISSUE THREAD

**Issue by CrysKilljoy** [Sollace/Presence-Footsteps#251]
Quality of the sounds is great, but really prominent and loud, and I would rather turn the sound down a good bit, but not the rest of the player sounds. 
I feel a seperate setting for that would be helpful. If there is a way to adjust that in a config, please tell me.

**Comment by Sollace** [comment]
There is a volume slider for presence footstep's sounds. Just press the shortcut (default: f10) whilst in-game to open the settings screen and adjust it there.

If you mean separate sliders for other players/mobs, I believe that was requested by someone before, just no issue created on here for it, which is probably why I forgot to do it.

Feel free to leave this open and I'll find some time to add it.

**Comment by Sollace** [comment]
There are already separate sliders for the player versus other players.
