### ISSUE TITLE
1.9.1 mod version for 1.20.1 doesn't work

### ISSUE THREAD

**Issue by Damglador** [Sollace/Presence-Footsteps#252]
I disabled all mods but fabric api and Presence Footsteps, and it just doesn't work.

**Comment by Damglador** [comment]
oh and when I switched mod version 1.9.0

**Comment by Sollace** [comment]
Did you enable the built-in resource pack for the default sounds?

**Comment by Damglador** [comment]
No, I didnt know it was necessary.
But looks like it works now, thanks!
