### ISSUE TITLE
[suggestion] upload LiteLoader builds of Presence Footsteps onto Modrinth

### ISSUE THREAD

**Issue by ColonelGerdauf** [Sollace/Presence-Footsteps#253]
This will make it a bit easier for those looking for the mods. Not to mention, the listing of LL mods in Modrinth is currently tiny even compared with Memfrey's site.

**Comment by ColonelGerdauf** [comment]
I was able to find the old liteloader builds in the GitHub release history, save for 1.7.2 (which I honestly don't think is significant enough to look for it).

As far as I can tell, it goes up from r5c to u11. (u11, u10, u8f and r5c being the most practically useful)

**Comment by Sollace** [comment]
> I was able to find the old liteloader builds in the GitHub release history, save for 1.7.2 (which I honestly don't think is significant enough to look for it).
> 
> As far as I can tell, it goes up from r5c to u11. (u11, u10, u8f and r5c being the most practically useful)

I've uploaded those versions for you
