### ISSUE TITLE
[bug?] Only Default Footsteps Play

### ISSUE THREAD

**Issue by Akorian** [Sollace/Presence-Footsteps#254]
Minecraft 1.20.1
Fabric 0.15.0
Presence-Footsteps 1.9.1
Windows 
Single Player

When joining a single player world and running around, I only hear the vanilla footstep noises. The mod is present and loaded. The settings don't have an option to active or deactivate the mod, also I didn't find any key bind apart from the one for the settings menu. I restarted the game multiple times. The mod has worked previously with a similar assortment of other mods and I also didn't find any mods that would conflict with Presence-Footsteps .

full_report.json: https://privatebin.net/?0597d9ec14595a14#3CBqqbnxik8Rv3znvdgrPGH56ASKDbrLJHPi9SYiim6q  (valid for 30 days)

Modlist: https://privatebin.net/?97ce7235241b070d#5hmTGY7ZnJrpNNt8S6k5hkHXDTgGxAGbzkGLwMzoNGPB (valid for 30 days)

**Comment by Murph2** [comment]
im having this exact same issue on 1.20.2

**Comment by Sollace** [comment]
Please make sure you have your built-in resource pack enabled for the presence footsteps sounds. It is configured to be enabled by default when you first install the mod, but it may appear as disabled for people who upgraded from a previous version of the mod.

The sounds are in a resource pack now to make it clear that people can customise the mod in that way (and they can fully replace it with their own sounds too)
