### ISSUE TITLE
[bug?] sounds not working correctly

### ISSUE THREAD

**Issue by ColdMt** [Sollace/Presence-Footsteps#255]
Minecraft 1.20.2
Fabric 0.15.0
mod 1.10.0
single player

there is no sound when jumping in place. only the sound of jumping of grass when initiating the jump. But no sound when landing.
Also when walking on anything other then grass or dirt, stopping also makes the sound of stopping on grass/dirt. 
I'll try to make a video later to show (probably more useful anyway)

Edit: I got the video: https://youtu.be/h_YGkYx1ju4

**Comment by Sollace** [comment]
Enable the built in sounds resource pack.

**Comment by ColdMt** [comment]
It is already enabled. u can hear it in the video. or is there another sound pack I am missing

![image_2023-12-18_191409491](https://github.com/Sollace/Presence-Footsteps/assets/80469108/1d6d5dbb-c52e-4d8f-a0df-6fa4279a453a)

**Comment by Sollace** [comment]
> It is already enabled. u can hear it in the video. or is there another sound pack I am missing
> 
> ![image_2023-12-18_191409491](https://private-user-images.githubusercontent.com/80469108/291372326-1d6d5dbb-c52e-4d8f-a0df-6fa4279a453a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjUyMDgsIm5iZiI6MTcwMjkyNDkwOCwicGF0aCI6Ii84MDQ2OTEwOC8yOTEzNzIzMjYtMWQ2ZDVkYmItYzUyZS00ZDhmLWEwZGYtNmZhNDI3OWE0NTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTYzNmMzY2VjZjA3Yzk4MWU1M2UxYjE5YzFhOGRmMzI5ZGE3MDAwYWMzZGQ5MTZkNDUzZjc0ODE1MTYwZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nx5yQSqbqWw77J5omOGJTLgdaMGNFzhvraEybnLBkUE)

Eeyup, I did not see that video. Sorry, thought this was the same issue as someone else saying there were not sounds.- I see now the landing sounds are not playing.

**Comment by ColdMt** [comment]
no problem, is it something I can change easily ?

**Comment by Sollace** [comment]
Unfortunately not. It's a bug introduced through the update, so I'm having to look into it.

(problem with the fall distance getting reset)
