### ISSUE TITLE
[Bug] Harsh sounds whist sprinting on dirt

### ISSUE THREAD

**Issue by Thanos1716** [Sollace/Presence-Footsteps#256]
When sprinting on dirt or farmland, the sound that plays gives the impression that the dirt is a hard block, comparing it to stone, it sounds even harsher. I'm not sure if this was intentional, but considering the sound that plays when walking instead of running, I think it most likely is a bug.
This can be disorienting when farming and the farmland is making a very hard sound.

Also the sound that plays when sprinting on coarse dirt/rooted dirt is quite harsh as well, but less so than dirt.

**Comment by Sollace** [comment]
This is just how the sounds are configured. It produces different types of sounds when sprinting versus walking.
