### ISSUE TITLE
Mod provokes a crash on Minecraft 1.20.4

### ISSUE THREAD

**Issue by janilowski** [Sollace/Presence-Footsteps#259]
Hello,

I am using `PresenceFootsteps-1.10.0.jar` with `modmenu-9.0.0-pre.1`, `fabric-api-0.91.3+1.20.4` and `fabric-loader-0.15.2-1.20.4`. The mod worked perfectly well in 1.20, however after the update to 1.20.4, the mod seemingly stopped working. 

When I enter the Mod Menu and click on options of PresenceFootsteps the game immediately crashed displaying the following message:

`Exit Code: 255`

```
The game crashed whilst mouseclicked event handler
Error: java.lang.IncompatibleClassChangeError: class com.minelittlepony.common.client.gui.element.Button overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
```

Not only do the options don't work, but I think the footsteps in general don't sound as nice. I'm not sure the mod is working at all after the new update.

**Comment by Sollace** [comment]
Install the 1.20.4 version of [kirin](https://github.com/MineLittlePony/Kirin/releases/tag/1.17.0%2B1.20.4) or wait for an update.

**Comment by Sollace** [comment]
you can update to this version now https://github.com/Sollace/Presence-Footsteps/releases/tag/1.11.1
