### ISSUE TITLE
con mods no suena cuando caminas

### ISSUE THREAD

**Issue by Jack406** [Sollace/Presence-Footsteps#26]
with terrestria, some blocks have no sound, it's something ugly

**Comment by aaron-sonin** [comment]
Same here. I'm not sure if it's the best solution, but would having default sounds for modded blocks based on material be a good idea?

**Comment by Sollace** [comment]
1. Sorry, I don't understand spanish.

2. I encourage everyone to look at the wiki for information on how to create their own resourcepacks to work with this mod.

https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators
