### ISSUE TITLE
[Issue] not working

### ISSUE THREAD

**Issue by tiigerbones** [Sollace/Presence-Footsteps#263]
for some reason when playing, it randomly stops working, player cant hear their own footsteps. mostly happens when going from mining to the surface.

the only other mod that messes with sounds is sound physics remastered but even when deactivated it still doesnt work properly.

running on fabric 1.20.1

**Comment by tiigerbones** [comment]
might of just been the fact that i had every compat and chipped installed together, creating too many block variants. gonna see if it happens with one them uninstalled (every compat)

**Comment by Sollace** [comment]
If there are mods that add very unique blocks that don't use the vanilla block sound types, then PF may have trouble figuring out what to make them sound like. For those you would have to specify the sounds to use for those blocks with a resource pack as described on the [wiki page](https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators) .

**Comment by tiigerbones** [comment]
ill make sure to look into that, but just a few moments ago i remained tabbed out for a few minutes and tabbed back into no footsteps being heard. i was standing over a standard grass block when i tabbed out.

**Comment by CoderXL1** [comment]
well, the mod didn't work for me too. the footsteps just never appeared, no matter how I changed the settings.
Mod Version: Presence Footstep 1.20.1-v1.9.1
[report_full.json](https://github.com/Sollace/Presence-Footsteps/files/13802615/report_full.json)

**Comment by Sollace** [comment]
> well, the mod didn't work for me too. the footsteps just never appeared, no matter how I changed the settings. Mod Version: Presence Footstep 1.20.1-v1.9.1 [report_full.json](https://github.com/Sollace/Presence-Footsteps/files/13802615/report_full.json)

YOU HAVE NOT ENABLED THE BUNDLED SOUNDS RESOURCE PACK

I am sick and tired of people not doing this and then saying tje mod is broken.
