### ISSUE TITLE
mod shows up in crashlog despite not being installed

### ISSUE THREAD

**Issue by mrsquid100** [Sollace/Presence-Footsteps#266]
i use my own private modpack of client and performance mods, and presence footsteps has never been installed in the modpack. 
yet when i try to launch my modpack on modrinth i see this in the latest log:
`[main/WARN]:
 Error loading class: eu/ha3/presencefootsteps/PFDebugHud (java.lang.ClassNotFoundException: eu/ha3/presencefootsteps/PFDebugHud)`

i also have only been getting this error after updating my pack from 1.20.2 to 1.20.4, even though all mods installed and enabled should be 1.20.4 compatible.

attachment: latest.log
[latest.log](https://github.com/Sollace/Presence-Footsteps/files/14000576/latest.log)
in(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

**Comment by Sollace** [comment]
Your crash is being caused by a mod named "spu".

You also have errors from something looking for sodium classes, which is not installed. Since none of the mods listed here made by me, there's nothing I can do here other than tell you to report your issues t9 the creators of the spu mod.

**Comment by mrsquid100** [comment]
thank you!
