### ISSUE TITLE
Is this problem?

### ISSUE THREAD

**Issue by shumaikun0415** [Sollace/Presence-Footsteps#267]
I have always enjoyed this mod.
however, When I was playing minecraft with this mod.
It depends on the location, but I hear a lot of footsteps even though no one is there.
Is there a solution to solve this problem?

**Comment by shumaikun0415** [comment]
sorry, I forgot to say ver1.20.1 fabric

**Comment by Sollace** [comment]
Are you maybe hearing footsteps from other mobs? There's an option to turn that off in the settings if you don't want it.
