### ISSUE TITLE
Footstep Sounds Don't Play Correctly

### ISSUE THREAD

**Issue by sdailey2001** [Sollace/Presence-Footsteps#27]
When standing on the North or South edge of a block with air to the side of it, no sound will play.
When on barriers, the block on the North or South side of where you're standing will play instead of nothing.

**Comment by Sollace** [comment]
I'm calling this working as intended. It's supposed to take sounds from both blocks you're standing on if you're standing between them.

**Comment by sdailey2001** [comment]
> 
> 
> I'm calling this working as intended. It's supposed to take sounds from both blocks you're standing on if you're standing between them.

Sorry, I didn't word this properly. I shall make a recording showing the issue instead, since it will be easier to explain.

**Comment by Sollace** [comment]
Alright. I'll be waiting around for a reply.

**Comment by sdailey2001** [comment]
Here it is: https://streamable.com/alnk4
