### ISSUE TITLE
I can't able to hear sounds from Copper and Tuff Backport

### ISSUE THREAD

**Issue by MotMomet** [Sollace/Presence-Footsteps#270]
It's actually weird but some of the step sounds from mod doesnt come when i have the some of step sounds and i can hear them like i can hear the "Chiseled Tuff" step sound but i can't hear the "Tuff Bricks" sound. I tried to use resourcepack to set the new blocks sounds to UNASSIGNED but still i can't able to hear the step sounds from mod. If you gonna ask is there a custom step sounds per block in the mod? the answer is yes. As i said above when i dont have the precense footsteps mod i can hear them. I know i can just use "stone" "marble" tags to add sounds to them but they have custom sounds and its better like that. I tried to add custom sound but im not good enough to make it happen im pretty low knowledge about it. 
![image](https://github.com/Sollace/Presence-Footsteps/assets/141963182/e4b6e971-62ad-4f74-8884-8644178764cd)
i tried this but didnt work. If i use different tags like stone and marble its working aswell so im not doing something wrong here i guess
![image](https://github.com/Sollace/Presence-Footsteps/assets/141963182/6a0d7739-96ef-485b-8e0f-cb447f0fbf8a)
i can hear the right block step sounds but cant hear the left ones its weird
there is report file i found after i use report button on config menu in the file it also shows the blocks as UNASSIGNED but i cant still hear the step sounds
![image](https://github.com/Sollace/Presence-Footsteps/assets/141963182/f6efefad-5616-4667-9751-857753a53a77)
here is the full report:
[report_full.json](https://github.com/Sollace/Presence-Footsteps/files/14163387/report_full.json)

i hope i can get help from here.. like any way to fix with resourcepack or something idk

**Comment by MotMomet** [comment]
if its not going to be problem, this is the mod i use
https://www.curseforge.com/minecraft/mc-mods/copper-tuff-backport-fabric
these are the sounds:
![image](https://github.com/Sollace/Presence-Footsteps/assets/141963182/061256ab-2f02-441c-aba5-2cef11766c31)
![image](https://github.com/Sollace/Presence-Footsteps/assets/141963182/f2126ed0-024d-47b3-9227-6c9e54eb9e00)
and yes placing sounds are working
also some of the copper blocks are not working aswell

**Comment by MotMomet** [comment]
And just noticed any other mod blocks like wall block doesnt have step sound but without precense footstep i have the sounds i think the problem is about UNASSIGNED tag ? (its default i didnt change anything just i saw it in the report.json)

**Comment by Sollace** [comment]
I don't assign sounds to modded blocks. If they use sounds the game already has, Presence Footsteps will pick sounds for them based on that, but if the mod is adding its own sounds (as is the case for the tuff backport mod) you have to assign them sounds yourself with a resource/sound pack.

**Comment by MotMomet** [comment]
> I don't assign sounds to modded blocks. If they use sounds the game already has, Presence Footsteps will pick sounds for them based on that, but if the mod is adding its own sounds (as is the case for the tuff backport mod) you have to assign them sounds yourself with a resource/sound pack.

how can i add custom sounds for precense footsteps?

**Comment by Sollace** [comment]
> > I don't assign sounds to modded blocks. If they use sounds the game already has, Presence Footsteps will pick sounds for them based on that, but if the mod is adding its own sounds (as is the case for the tuff backport mod) you have to assign them sounds yourself with a resource/sound pack.
> 
> how can i add custom sounds for precense footsteps?

There's information for how to do that on the wiki here: https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators

You probably want either the blockmap.json that specifies a material per block state, or the primitives.json which specifies it per sound type which you can get from either the full or concise reports.

The default sound pack (here: https://github.com/Sollace/Presence-Footsteps/tree/1.20.4/src/main/resources/resourcepacks/default_sound_pack ) can be used as an example. :)
