### ISSUE TITLE
Backport `1.10.1`/`1.11.1` fixes to 1.20.1

### ISSUE THREAD

**Issue by CarlMichaelFabe** [Sollace/Presence-Footsteps#272]
Any plans on backporting the fixes in `1.10.1`/`1.11.1` to MC 1.20.1? Especially fixes for sneaking not silencing player's footsteps and jump sounds not being played.
Thanks in advance.

**Comment by Sollace** [comment]
Possibly. I expected most people would be playing at least 1.20.2 or 1.20.4 by now. Unfortunately I don't really have the time to look at doing any backporting at the moment. When I do get to it I will backport the next update along with whatever fixes are relevant to that version.
