### ISSUE TITLE
Presence footsteps and Dynamic surroundings canceling out each other.

### ISSUE THREAD

**Issue by jjjaayyy** [Sollace/Presence-Footsteps#273]
I don't know if you can use the 2 mods together but when I have both mods in my game, PF stops DS from working no matter how much I tweak the settings in both mods. My game version is 1.20.1

**Comment by Sollace** [comment]
Presence Footsteps only replaces the footstep sounds the player hears and makes. It doesn't do anything else that would affect dynamic surroundings. I suggest reporting this to them instead,
