### ISSUE TITLE
waaaaaaaaaaaaaaaaaaaaay too loud

### ISSUE THREAD

**Issue by FxRadiation** [Sollace/Presence-Footsteps#28]
im not sure if there is an option to change this but i feel the sounds of walking around is too loud.
if this is changeable or a glitch please say so

**Comment by Sollace** [comment]
F10 -> change the volume slider

**Comment by FxRadiation** [comment]
F10 doesn't do anything for me

**Comment by Sollace** [comment]
Do you press it whilst in game, or in the settings screens? Should work when you're in game.

**Comment by FxRadiation** [comment]
Oh sorry I think it was because I didn't have fabric mod menu installed

**Comment by FxRadiation** [comment]
Oh nevermind when you asked me to do it I had the mod uninstalled but it works now since I reinstalled it but I didn't know about the key binding thanks
