### ISSUE TITLE
[1.20.1] - Mod seems to crash the game upon creating/joining a new world

### ISSUE THREAD

**Issue by Allexio** [Sollace/Presence-Footsteps#281]
I'm a bit busy right now but will add some more info here later.
I'm using quite a few mods but disabling this one specifically lets me actually continue to the game.
Will update this soon, sorry about the lack of info in here.

**Comment by Allexio** [comment]
Okay maybe it was just a freak bug, I can't seem to replicate it anymore.
Will open a new issue if it happens again and will make sure I get the error logs.

**Comment by Allexio** [comment]
Re-opened the issue following last comment.

**Comment by Sollace** [comment]
Duplicate of #282
