### ISSUE TITLE
Crash On Loading World

### ISSUE THREAD

**Issue by serioos** [Sollace/Presence-Footsteps#282]
The mod was working, but I saw an update, and updated it just now from version PresenceFootsteps-1.9.0.jar to PresenceFootsteps-1.9.2.jar on Minecraft version 1.20.1 Fabric and now it crashes to the desktop with this crash log whenever I try to load the save:

https://pastebin.com/MsP0gQeS

**Comment by Paxx3** [comment]
I got a same issue here. It crashed my world when i created a new one, Here is my crash and logs.


LOG ( I got a EMI mod issue, it spams the logs only when a crash happens) : https://mclo.gs/sitfQRn

CRASH: https://mclo.gs/jaepFbi

**Comment by Sollace** [comment]
Try deleting your presencefootsteps config

**Comment by ablehobo** [comment]
Was having the same issue and can confirm that deleting userconfig.json in the config folder seems to fix it.

**Comment by serioos** [comment]
I deleted it, and it stopped the crash, but now the mod is not working at all. I hear default footstep noises whereas I heard weighty footsteps before.

**Comment by Sollace** [comment]
Now go into the settings (F10) and toggle the mod on and turn up the master volume. It should default to being on with a new config. Might be another bug I have to look at.

**Comment by serioos** [comment]
I did try toggling it on and off, but didn't touch the master volume. Toggling didn't do anything.

**Comment by Sollace** [comment]
> I did try toggling it on and off, but didn't touch the master volume. Toggling didn't do anything.

Do you have the Default Sounds resource pack enabled?

**Comment by serioos** [comment]
I didn't mess with any of the sound resource packs. I guess the default should be on by itself?

**Comment by LivingSkeleton11** [comment]
I was having the same problem and followed the steps here (delete config) which worked, but now I'm also only hearing default step sounds. I don't have the default sounds pack on, and have turned off all my resource packs, but still only hear the default Minecraft sounds. Toggling the sounds on/off and changing the master volume did nothing. I tried generating a report but got the following error:

> Failed to generate report: java.lang.NullPointerException: Cannot invoke "eu.ha3.presencefootsteps.sound.generator.Locomotion.name()" because the return value of "java.util.Map.get(Object)" is null

**Comment by Sollace** [comment]
> I was having the same problem and followed the steps here (delete config) which worked, but now I'm also only hearing default step sounds. I don't have the default sounds pack on, and have turned off all my resource packs, but still only hear the default Minecraft sounds. Toggling the sounds on/off and changing the master volume did nothing. I tried generating a report but got the following error:
> 
> > Failed to generate report: java.lang.NullPointerException: Cannot invoke "eu.ha3.presencefootsteps.sound.generator.Locomotion.name()" because the return value of "java.util.Map.get(Object)" is null

Please turn on the default step sounds resource pack

**Comment by Sollace** [comment]
I'm marking this as fixed as the issue that causes the crash has been fixed.

Until the next release, please delete your presencefootsteps.json (don't touch anything else) and let the mod generate a new one to resolve the crash.
