### ISSUE TITLE
No custom footstep sounds (mod doesn't work) (1.20.4, mod version 1.11.2)

### ISSUE THREAD

**Issue by LivingSkeleton11** [Sollace/Presence-Footsteps#285]
After installing the mod into my modpack and facing the issue where there are no footstep sounds at all (resolved), there are only vanilla footstep sounds, and the mod seemingly does not work at all. I've turned off all of my resource packs, Presence (and Fabric API) are the only mods in my mods folder, toggled all sounds on/off in the in-game mod settings (F10), changed the volume slider, I've deleted both the "presencefootsteps" and config folders, and then reinstalled the mod and let them regenerate, all to no avail.

I tried to generate a debug report using the ingame menu, but get the following error: 

> Failed to generate report: java.lang.NullPointerException: Cannot invoke "[eu.ha3.presencefootsteps.sound.generator.Locomotion.name](http://eu.ha3.presencefootsteps.sound.generator.locomotion.name/)()" because the return value of "java.util.Map.get(Object)" is null

https://github.com/Sollace/Presence-Footsteps/assets/58710548/7bb29765-3bab-437d-81ff-a6ea0f0b8d2c

**Comment by Sollace** [comment]
Enable the built-in resource pack. I am getting sick of having to tell people to do this.
