### ISSUE TITLE
footstep sounds play while in mid-air

### ISSUE THREAD

**Issue by Confusified** [Sollace/Presence-Footsteps#288]
on the 1.11.2 version of PresenceFootsteps it plays footstep noises while in mid-air.
i've been able to reproduce it by simply jumping and flying in creative

it does not happen when moving in any direction besides vertically

**Comment by PaulRV0709** [comment]
Same issue on the 1.9.2 version of the mod in 1.20.1

**Comment by Sollace** [comment]
I don't see this issue on my end. Not either in dev or when playing on a friend's server.

**Comment by ComradeCaro** [comment]
I also have the issue when standing still mid-air in creative or when moving vertically. The sound appears to spawn in at regular intervals. As mentioned earlier this happens on 1.20.1, version 1.9.2 of the mod

**Comment by ComradeCaro** [comment]
Also happens on v1.9.1

**Comment by MaixGit** [comment]
Bump.
Happening on Minecraft 1.20.4 with version 1.11.2, same experience as [Confusified](https://github.com/Confusified). Just in case this hasn't been fixed for the next release.

**Comment by Sollace** [comment]
This has already been fixed and is pending release (soon as I can finish some other side tasks). Thanks everyone for the report
