### ISSUE TITLE
Armor stands make all nearby footsteps sound like stone.

### ISSUE THREAD

**Issue by djmrFunnyMan** [Sollace/Presence-Footsteps#289]
Pretty self explanatory. Armor stands for some reason make all nearby blocks default to the stone footsteps sound.

https://github.com/Sollace/Presence-Footsteps/assets/68905776/d5eeeb90-2472-4f0d-b8bb-803979c077f0

**Comment by Sollace** [comment]
I cannot reproduce this. In fact it seems to be doing the opposite: I hear the footsteps from the block below even when I walk directly inside the armor stand.

Is the built-in resource pack enabled on your client?
