### ISSUE TITLE
Game crash at start

### ISSUE THREAD

**Issue by Solifax** [Sollace/Presence-Footsteps#29]
For some reason my game keeps on crashing. Im using the latest version of fabric on Minecraft 1.14.4. works fine if i remove P-F.. Any ideas?
It is a real bummer since I loved playing with MAtmos and P-F back in 1.7.10.

**Comment by Sollace** [comment]
Did you install fabric-api? 

https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Solifax** [comment]
well, no.. just did. and still nothing :(

**Comment by Sollace** [comment]
Then please send the crash report.

**Comment by HEROBRIONE5** [comment]
I have the same issue, and I've narrowed it down to PF as well. I'll attach my crash report.
[crash-2019-10-19_15.52.36-client.txt](https://github.com/Sollace/Presence-Footsteps/files/3747121/crash-2019-10-19_15.52.36-client.txt)

**Comment by Sollace** [comment]
@HEROBRIONE5 Try deleting your config file for PF. I'll try looking at the cause later.
