### ISSUE TITLE
Soul Soil is playing too many sound effects.

### ISSUE THREAD

**Issue by djmrFunnyMan** [Sollace/Presence-Footsteps#292]
While in the nether that walking on soul soil makes more footstep sounds than walking on any other block. I think it's playing them twice for some reason.
Here's a comparison between soul soil:
https://github.com/Sollace/Presence-Footsteps/assets/68905776/c9747171-b457-454f-9cc1-74c026d4ae1e

And dirt
https://github.com/Sollace/Presence-Footsteps/assets/68905776/8ce657ec-5614-4419-b423-e04c9982d1aa

**Comment by djmrFunnyMan** [comment]
The embed broke, I can resend if you cannot play the video (I encoded it weird)

**Comment by Sollace** [comment]
This sounds like what it's supposed to be

**Comment by djmrFunnyMan** [comment]
Are you sure? When walking around I can definitely hear two sounds playing at once which doesn't happen with any other block. At least maybe make it quieter or some adjustments.

**Comment by djmrFunnyMan** [comment]
I think it's cuz the walking footstep sound and "stopping sound" (idk how to call it, the footstep sound that happens when you stop) is exactly the same. I think that sound is usually different from the normal footsteps noise and quieter.

**Comment by djmrFunnyMan** [comment]
Here's a video of me definitely making a double sound when landing

https://github.com/Sollace/Presence-Footsteps/assets/68905776/8f2507f3-1003-41a5-8663-a6181fbea572

And here's a comparison between jumping on wood/soul soil

https://github.com/Sollace/Presence-Footsteps/assets/68905776/3057cb61-3af8-4662-8b3f-22c21350656a

**Comment by Sollace** [comment]
Okay I see what's happening.

The mod simulates each foot separately, but just to double-check, go to the settings and verify that you have stance set to bipedal.

**Comment by Sollace** [comment]
Checking the acoustics file, there is an additional sounds played with a delay of 50 when landing. This update specifically fixes issues with delays not being applied, so it does appear to be intentional

```
        "quicksand": {
            "type": "events",
            "walk": "quicksand.quicksand_walk",
            "wander": "dirt.dirt_wander",
            "land": [
                "sand.sand_run",
                {
                    "type": "basic",
                    "name": "quicksand.quicksand_walk",
                    "volume": 50.0
                },
                {
                    "type": "delayed",
                    "delay": 50,
                    "acoustic": "quicksand.quicksand_walk"
                }
            ]
        },
```

**Comment by djmrFunnyMan** [comment]
yes I did have a bipedal stance selected, if it's intentional then I suggest it be changed that's all

**Comment by Sollace** [comment]
Figured out what the problem is: The jump and land sounds are the same.

It's not doubled, it just plays the same thing for both when you jump off and land on the block. If all you do is stand in one place and jump constantly they will play very close to each other and create the effect heard in your second video.

**Comment by djmrFunnyMan** [comment]
There are two other blocks affected
Magma/campfires and honey blocks (not slime blocks for some reason)

https://github.com/Sollace/Presence-Footsteps/assets/68905776/25206399-2d91-4c9d-9337-14d7f36b5a5e

https://github.com/Sollace/Presence-Footsteps/assets/68905776/cb439cf0-e63e-4789-b7e7-26f34aed2695

Honey blocks are honestly so obscure it doesn't matter and it doesn't even sound too bad.
However walking on magma is so unpleasantly loud and because the "steam" sound effect is so long and you can stack many at once.
I suggest making the steam sound quieter, it sounds a lot better with that tweak imo. (video with the fix below)

https://github.com/Sollace/Presence-Footsteps/assets/68905776/cddc7729-bb83-4da9-86a6-e415ea4acf17

**Comment by djmrFunnyMan** [comment]
(@Sollace in case you missed it cuz I don't wanna open another issue for this)
