### ISSUE TITLE
High speed sprinting sound get throttled on 1.11.2

### ISSUE THREAD

**Issue by rikumi** [Sollace/Presence-Footsteps#294]
When sprinting at high speed (wearing totally +140% speed armors in my case), PF 1.11.1 would yield sounds more frequently in respect of the speed. After updating to PF 1.11.2 for 1.20.4, the sounds get throttled to no more than 2 times per second.

**Comment by Sollace** [comment]
This is intentional - as riding horses would result in rapid-fire footsteps. Twice per second sounds like it's too slow. It should probably allow it to go quicker than that.
