### ISSUE TITLE
1.7.10?

### ISSUE THREAD

**Issue by enterprise12nx** [Sollace/Presence-Footsteps#3]
Can you apply the changes you have made to the 1.7.10 version?
would be great, ty

**Comment by Sollace** [comment]
Sorry, I'm not going to support versions that old.

**Comment by enterprise12nx** [comment]
ah thats a shame, so many people use 1.7 still

**Comment by jochuan** [comment]
it is time to update

**Comment by enterprise12nx** [comment]
Meh i beg to differ, minecraft 1.9 is stupid, this isnt an RPG, and most people agree on that note, 1.8 came out with nothing special, especially for modpack authors, nobody generally cares to update past 1.7.10 since it gives nearly no changes besides 2 biomes(which mods already provide) and temples (yawn).
There are only a few handfuls of 1.8 mods that are out currently, for small mods i guess its easier to update to 1.7+ but a majority of players still use 1.7
