### ISSUE TITLE
Footstep sound for walking on water

### ISSUE THREAD

**Issue by NolanHewitt** [Sollace/Presence-Footsteps#302]
While not possible without mods, walking on water currently makes no sound at all. It would be nice to have some kind of splashing puddle sound for this particular occurrence.

**Comment by djmrFunnyMan** [comment]
Adding to this. Do the same for lava. Probably should either reuse the strider footstep sounds from vanilla, since it's like the official sfx for walking on lava.

Or reuse the sounds from walking on magma blocks.
