### ISSUE TITLE
Could you add settings for generated subtitles please? Or at least the ability to return to vanilla subtitles

### ISSUE THREAD

**Issue by TheCrossCarrier** [Sollace/Presence-Footsteps#304]
Hello Dear <3

Could you add settings for generated subtitles please? Or at least the ability to return to vanilla subtitles

Thanks!

**Comment by Sollace** [comment]
I'm sorry, but isn't the vanilla subtitles all just "Footsteps"?

**Comment by TheCrossCarrier** [comment]
@Sollace  I actually use subtitles to detect nearby hostile mobs. But the mod creates more subtitles compared to the vanilla version and it is more difficult to notice what you really need.

**Comment by Sollace** [comment]
With the way the game does subtitles I don't think there's any easy way I can do this.

The subtitles are determined by the sound being played, not by what is playing those sounds. My suggestion if you want the original subtitles is to change the target selector in the settings to [Players Only]. That way Presence Footsteps will only change you and other players' footsteps and leave mobs untouched.

**Comment by TheCrossCarrier** [comment]
I found this mod https://modrinth.com/mod/verbose-subtitles. It allows you to remove certain subtitles, but I haven’t figured out how to configure it correctly :(

**Comment by Aexakos** [comment]
I am not the affiliated with the mod and I do not know if the mod's license permits it, but here's how you can achieve that easily. Open the presencefootsteps.jar as a rar, navigate to assets/presencefootsteps/lang directory. Open "en_us.json" (or whatever language you use) and scroll to the bottom of the text. There from "subtiles.pf.wood_squeak" and onwards remove the inside of the quotations marks from the right side of the colon symbol.
It should look like this: "subtitles.pf.wood_squeak": "", "subtitles.pf.wood_bends": "", ... and so on
