### ISSUE TITLE
[Enhancement] Integration with Crawl mod

### ISSUE THREAD

**Issue by Exokyhh** [Sollace/Presence-Footsteps#306]
It would be nice if this mod added integration with the Crawl mod (https://modrinth.com/mod/crawl), since even if you are crawling, you will still hear the footsteps sound. It should behave like sneaking, where no sound is heard.

**Comment by Sollace** [comment]
If the intention is for the player to not produce footstep sounds whilst crawling, the Crawl mod should ensure the player returns true for `Entity.isSneaky()`.

This is not really something that Presence Footsteps should have to fix.
