### ISSUE TITLE
One layer of snow play sound of block beneath

### ISSUE THREAD

**Issue by AlexGBRV** [Sollace/Presence-Footsteps#308]
Fabric 1.20.1
Presence Footsteps 1.9.2

One layer of snow play sound of block beneath. When there are more layers of snow on the block, everything is fine.

**Comment by Sollace** [comment]
Update to 1.9.3 please

https://github.com/Sollace/Presence-Footsteps/releases/tag/1.9.3

**Comment by AlexGBRV** [comment]
Thank you! Now everything works correctly. I haven't checked that there is a newer version on Modrinth (on CurseForge only 1.9.2). ModMenu did not show that there was an update.

**Comment by Sollace** [comment]
Yeah I intend on enabling the mod menu update checking soon. Good to hear it's fixed!
