### ISSUE TITLE
[1.15-pre4] crash when starting gameclient

### ISSUE THREAD

**Issue by Gbergz** [Sollace/Presence-Footsteps#31]
(Could be because of other mods conflicting?)

**Fabric API**: _0.4.19+build.272-1.15_
**MC Ver**: _1.15-pre4_
**Mod Ver**: _1.15-pre3-r18_

**Crash-Report**: [https://paste.ee/p/TPzdO](https://paste.ee/p/TPzdO)

If this is because of it not being updated pre4 excuse me! :)

**Comment by Sollace** [comment]
You're using modmenu. I'm uploading a fix for this now.

**Comment by Sollace** [comment]
https://github.com/Sollace/Presence-Footsteps/releases/tag/r19
