### ISSUE TITLE
v1.9.4 not compatible with 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [Sollace/Presence-Footsteps#310]
![image](https://github.com/Sollace/Presence-Footsteps/assets/120551916/a79ac5ab-e358-4946-a83b-3c68aa3e3933)

**Comment by blackrx330** [comment]
Change the mod version with WinRAR or something similar 
![image](https://github.com/Sollace/Presence-Footsteps/assets/54097369/2843019b-dca8-41dc-9633-cda50335526e)

**Comment by Sollace** [comment]
:ohno-emoji:

**Comment by Sollace** [comment]
Fixed. You can redownload it from the release page.
