### ISSUE TITLE
Some sound seem to be missing (slow walking over wheat/crops?)

### ISSUE THREAD

**Issue by hiimrickross** [Sollace/Presence-Footsteps#311]
Hello! Absolutely adore this mod.

Now off the bat, I don't know if it's a mod incompatibility or not. All I know is that it DID work in my old instance of Prominence Classic 2.7.0, and it still DOES work now after updating mods after many months not playing (and also updating Sinytra Connector from v36 to v41 or 42) but on your YouTube video demonstrating the mod, there is crunchy sounds when walking through wheat (just walking) however on mine it is silent. if I run though, then I get sounds for wheat, and the crunchy dry fully grown wheat vs less intense sound for growing wheat.

Sometimes I have a resource reload failure error too on loading, though this seems to be a symptom of a mod incompatibility as after I revert the update on some mods, or delete the new one outright that causes it, I can properly select & reload over and over resource packs.

I notice also that I can set the resource packs, remove one reload, add it back reload, etc... But then when I go into a world, play for a bit, then save & quit and try to do the same thing, the resource reload fails.

That plus the missing crop fx seems to imply to me there is some odd incompatibility but it's not logged or impeding gameplay critically (crash).

**Comment by Sollace** [comment]
Check the settings and make sure the volume for brushes isn't turned down. It has its own slider now since people didn't like them.

**Comment by Sollace** [comment]
Oh also the current version has support for footwear, which you can turn off as well. When wearing boots it won't produce as much brush sounds which might be what you're experiencing.

**Comment by hiimrickross** [comment]
Thanks for the information. I couldn't see the slider for brushes specifically, although that might be a slider on 1.9.4 which I hadn't checked yet. I will say though, my "normal walking speed" brush/bush/foliage sounds seem to have returned (whereas before I would only hear them when sprinting). What fixed it? I'm not quite sure... I've been troubleshooting a lot of things at the same time, but I do believe it was still no triggering on v1.9.4, so it must have been a conflict somewhere, even if I don't have mods that should be touching it :/

Either way - the resource reload failure problem I mentioned was fixed (problem: mythic upgrades on sinytra), so that wasn't presence footsteps problem. The missing sounds still happened too, after that, so it wasn't related.

For the time being it seems to be back (sinytra v43/latest suite). But I will have to go over my changes and see if anything stands out that might have fixed it. 

It may also have been an incompatibilty with simple hats, curios, and emi - as the former would sometimes fail loading emi with a critical error in-game, then when I updated curios & emi, it would ALWAYS error, until I updated simplehats. The reason I think maybe it's related to this is 1) first time I noticed Presence Footsteps sounds being back was after I did this and 2) when EMI would fail, the dropped item nameplates mod (cannot remember the name, often paired with loot beams) wouldn't display names for low grade/normal items.

Either way - while it definitely was an issue (bizarre that every other sound seemed to be playing fine!) something along the way seemed to have fixed it. I'll update my thread later with a list of mod/changes just in case someone in the future experiences a similar behaviour. Thanks for your time.

**Comment by Sollace** [comment]
Alright. Also for the missing sounds, try my other suggestion and turn off footwear. With the option enabled wearing boots will prevent brush sounds from playing.

(Option for it might be called foliage by the way)

**Comment by hiimrickross** [comment]
> Alright. Also for the missing sounds, try my other suggestion and turn off footwear. With the option enabled wearing boots will prevent brush sounds from playing.
> 
> (Option for it might be called foliage by the way)

Omg you're right.. I didn't think that was a feature (how wearing shoes mutes the walking brush/foliage fx and only has it play when running). I just put on some shoes and then took them off and yep that's how it behaves.... Feel kind of silly thinking it was a mod conflict then.

I tried toggling the "Footwear" setting to remove that (I'd like foliage sounds to be on all the time shoes or not) but it didn't seem to make a difference, does it require a reload?
