### ISSUE TITLE
Blocks with custom materials do not play footstep sounds at all.

### ISSUE THREAD

**Issue by Mickeon** [Sollace/Presence-Footsteps#312]
Hello. Let me preface by saying that this mod's default features and sound pack are really neat and satisfying to hear.

I just want to note that it seems like any block with new materials do not play any footstep noises **at all**. I've tested this with Alex's Caves Guano Block & Hazmat Blocks, Supplementaries' ropes and the list may go on.

While it seems to be possible to redefine the sound event manually for this mod to interpret, that is time spent on something additional I'm not sure it's worth the time for.

If Presence Footsteps has no equivalent "enhanced" sound, the default stepping noise that Minecraft would use should play. This does not seem to be currently the case, even though it's stated that's what should happen. https://github.com/Sollace/Presence-Footsteps/wiki/Resourcepacks:-Blockmap.json#value-syntax

The current version of the mod is `1.9.4`. Playing on Minecraft 1.20.1, using Forge (through the [Sinystra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)).

**Comment by Sollace** [comment]
Hm yeah, this may be an unintended consequence of the last fixes, or a much older bug that's been there for a while.
