### ISSUE TITLE
[Enhancement] Bring some vanilla blocks sounds (idk how to call this)

### ISSUE THREAD

**Issue by RedCarlos26** [Sollace/Presence-Footsteps#314]
I don't know if this is an oversight, but some blocks like the netherrack use the default "stone" or "brick" sound, even though they now have amazing sounds which Mojang added in prior updates.

Examples :
Netherrack (the most obvious)

Netherbricks (maybe, haven't checked yet but is possible since the netherrack isn't the vanilla sound
Netherite_block (idk if this one is modified or not)

**Comment by zndrmn** [comment]
You can change these sfx with a resource pack. I changed the netherrack blocks to sound more soft and less moist and it sounds great now.
