### ISSUE TITLE
Whenever i back out of the game and go back into it, the mod turns it self off

### ISSUE THREAD

**Issue by darknrgz** [Sollace/Presence-Footsteps#315]
Simple as that. not sure if im doing something wrong or if theres a setting i need to have on/off

**Comment by cosmichero2025** [comment]
On version version 1.20.1 using fabric and the version of the mod posted on May 15th. Experiencing this issue as well but can't find the the conflicting mod. The mod works but I have to toggle it on everytime. I'd be fine for me but I'm making this modpack for like 50ish people and I'd like it to be automatic

**Comment by Sollace** [comment]
I presume this isn't an issue with the mod but with an external manage, like @cosmichero2025 said?

Going to close this in the meantime. If it's still an issue using nothing else but this mod and fabric, feel free to open a new one.
