### ISSUE TITLE
Crash on startup Forge with Sinytra Connector.

### ISSUE THREAD

**Issue by KeylorV** [Sollace/Presence-Footsteps#316]
Basically is asking me for a Fabricloader, wich, it shouldn't when its already said in the curseforge page to use sinytra connector..
[Crashlog.txt](https://github.com/Sollace/Presence-Footsteps/files/15450121/Crashlog.txt)

**Comment by Sollace** [comment]
Synatra connector provides an implementation of fabric loader. You need to update synatra connector or report this error to them
