### ISSUE TITLE
Add text introduction about sound pack thing in README

### ISSUE THREAD

**Issue by boholder** [Sollace/Presence-Footsteps#318]
Hi, thanks for this amazing mod, it helps visually impaired (blind) players playing this game better, almost all of them installed this mod.
I'm one of developers of [minecraft-access](https://github.com/khanshoaib3/minecraft-access) mod, the one for adding visual accessibility to this game.

One of my user was confused about installing this `Presence-Footsteps` mod, after chatting we realized that is because [the sound pack part of README](https://github.com/Sollace/Presence-Footsteps?tab=readme-ov-file#sound-packs) isn't mentioning "you need to select resource pack in menu" in text, but in image, which makes blind user missed this step.

Would you like to add this part in README and [Modrinth page](https://modrinth.com/mod/presence-footsteps)?

**Comment by Sollace** [comment]
You shouldn't have to select the sound pack at all. It's enabled by default on a fresh install.

If it's not, that's likely a quilt bug I reported to them a while ago as I was never able to replicate it with fabric.

**Comment by boholder** [comment]
Ok?... My user said she's using Fabric but yeah we really can't figure out it. Thanks for replying.
