### ISSUE TITLE
Entities (animals) cause huge lag when using this mod with Sound Physics

### ISSUE THREAD

**Issue by VL4DST3R** [Sollace/Presence-Footsteps#324]
Note: This is something of a cross-post between this project and Sound Physics where I have posted [a similar thread](https://github.com/henkelmax/sound-physics-remastered/issues/224).

I have reasons to believe Sound Physics is the main culprit in my situation, but I couldn't help but notice how the issue gets compounded when used in conjunction with this mod, so I figured mentioning it on both ends was the best course of action.

I've read that an issue related to performance issues with entities was [already reported and presumably fixed](https://github.com/Sollace/Presence-Footsteps/issues/218) before, but after recently updating Presence Footsteps from `PresenceFootsteps-1.9.1` to `PresenceFootsteps-1.9.4+1.20.1` (among a few other unrelated mods) I started to notice that in one particular area of my base where it was previously fine performance-wise, now I would get notable fps drops when inside the room.

![image](https://github.com/henkelmax/sound-physics-remastered/assets/32654378/26790e38-a671-4496-a482-bdd673142ccb)

BUT ONLY IF Sound Physics is also installed/enabled (which I also had previously running together with this one just fine). This causes the game to drop to ~1fps and becomes completely unplayable.

Any advice what may be causing this?

**Comment by Sollace** [comment]
There's nothing particularly noteworthy that we're doing different in this version. Is is perhaps because sound physics is trying to do processing on the step sounds the mobs are making?

We do have a setting to reduce the cap on simultaneous sources (so mobs in the same area get collapsed down into a single source). Maybe try changing that setting?

**Comment by Sollace** [comment]
I'd also suggest you try changing the target mod in PF's settings to players only to maybe narrow down the cause to the mobs.

**Comment by VL4DST3R** [comment]
> I'd also suggest you try changing the target mod in PF's settings to players only to maybe narrow down the cause to the mobs.

Tried this already and indeed the impact was reduced.

> We do have a setting to reduce the cap on simultaneous sources (so mobs in the same area get collapsed down into a single source). Maybe try changing that setting?

Will try this as well. Was the cap changed anytime recently?

**Comment by Sollace** [comment]
> > I'd also suggest you try changing the target mod in PF's settings to players only to maybe narrow down the cause to the mobs.
> 
> Tried this already and indeed the impact was reduced.
> 
> > We do have a setting to reduce the cap on simultaneous sources (so mobs in the same area get collapsed down into a single source). Maybe try changing that setting?
> 
> Will try this as well. Was the cap changed anytime recently?
> 
> Edit: where can I find this option?

The option is in the config file. It's alled "maxSteppingEntities" and has a default of 50.

**Comment by Sollace** [comment]
Closed as stale. I presume fixed by changing the config
