### ISSUE TITLE
Sounds completely silence periodically (necessiting a F3+T to come back)

### ISSUE THREAD

**Issue by vico93** [Sollace/Presence-Footsteps#329]
I'm opening it here because it's the only mod that touch sound (that i'm aware) on my modpack.

Basically, when playing either in singleplayer or multiplayer (in 1.21), after a while the whole sounds (Presence Footsteps and vanilla) just went silent, necessitating a resource reload to came back. Don't know how to troubleshoot this, my pack is fairy large, but aside of Voicechat (that i only activate on multiplayer sessions), this is the only other mod that directly touch the sound of the game, like i said above.

Version 1.10.0+1.21

**Comment by Sollace** [comment]
The mod plays sounds but it doesn't touch the sound internals. If the issue you're having is affecting vanilla sounds outside of footsteps there may be something else going wrong.

**Comment by vico93** [comment]
> The mod plays sounds but it doesn't touch the sound internals. If the issue you're having is affecting vanilla sounds outside of footsteps there may be something else going wrong.

Sorry to forgot to update this issue, this really have nothing to do with Presence Footsteps, it was another mod that was causing this.
