### ISSUE TITLE
1.15 requires kirin

### ISSUE THREAD

**Issue by aliyuchang33** [Sollace/Presence-Footsteps#33]
![图片](https://user-images.githubusercontent.com/22322294/70840999-ad7c2500-1e51-11ea-907f-c58f6d0ae617.png)
I'm using the latest 21 version from release but it failed to start just like in the picture. I cannot find `kirin` mod on the internet.

**Comment by Sollace** [comment]
Oh, whoops. It's supposed to be included, but you can install Kirin manually from over here:

https://github.com/MineLittlePony/Kirin/releases/tag/1.5

It's a UI lib used for building the settings screen, if anyone's curious.

**Comment by Sollace** [comment]
Update: I did check and Kirin does seem to be in the jar. Not sure why it isn't loaded

**Comment by aliyuchang33** [comment]
Installing fabric-api solved the issue

**Comment by Sollace** [comment]
Ah, right. Though odd that it wouldn't say "fabric-api" is missing.
