### ISSUE TITLE
Zombie footstep caused crash

### ISSUE THREAD

**Issue by Barerock** [Sollace/Presence-Footsteps#331]
[crash-2024-07-28_00.24.36-client.txt](https://github.com/user-attachments/files/16402203/crash-2024-07-28_00.24.36-client.txt)
[latest.log](https://github.com/user-attachments/files/16402204/latest.log)

Forge 47.2.20
MC 1.20.1

**Comment by Sollace** [comment]
I do not maintain the forge fork. Please report it to them https://github.com/PaintNinja/Presence-Footsteps-Forge
