### ISSUE TITLE
Crash games

### ISSUE THREAD

**Issue by Sergo467** [Sollace/Presence-Footsteps#333]
Minecraft 1.20.1
Forge 47.2.20
Sinytra Connector 1.0.0-beta.44+1.20.1
Presence Footsteps 1.9.0
Here is the crash log
https://gist.github.com/Sergo467/6a8cf30efd8b8fa06ee64905989bdb27

**Comment by Sollace** [comment]
Please update the mod to version 1.9.5 and test using Fabric to see if the problem still happens.

https://github.com/Sollace/Presence-Footsteps/releases/tag/1.9.5%2B1.20.4
