### ISSUE TITLE
[Bug] Random vanilla footstep SFX playing

### ISSUE THREAD

**Issue by zndrmn** [Sollace/Presence-Footsteps#335]
#### You'll probably have to turn this up, also there's subtitles in the bottom right.
I have the RP enabled, and the only mods I have installed are sodium and presence footsteps (and fapi)

https://github.com/user-attachments/assets/fe9c3b45-39cc-46d4-837f-605d79db0d92

**Comment by zndrmn** [comment]
#321 seems to still be an issue after testing without any other mods installed but presence footsteps and sodium

**Comment by Sollace** [comment]
This is a persistent bug. What version are you using?

**Comment by zndrmn** [comment]
`PresenceFootsteps-1.11.3.jar`
I should probably test 1.21 (using the latest 1.20.4 version)

**Comment by Sollace** [comment]
I cannot reproduce this in the 1.21 version so I have to close this
