### ISSUE TITLE
[1.20.1][Sinytra] Incompatible with Create v0.5.1h

### ISSUE THREAD

**Issue by DeshiDesu** [Sollace/Presence-Footsteps#337]
> Forge 47.3.7
> PresenceFootsteps-1.9.4+1.20.1.jar
> create-1.20.1-0.5.1.h.jar
> Connector-1.0.0-beta.45+1.20.1.jar
> fabric-api-0.92.2+1.11.8+1.20.1.jar

With the recent update of [Create](https://www.curseforge.com/minecraft/mc-mods/create/files/5689514), new changes were made which ultimately broke PresenceFootsteps' integration with Create. The last working version between Create and PF was [v0.5.1f](https://www.curseforge.com/minecraft/mc-mods/create/files/4835191).

> [pool-4-thread-1/FATAL] Mixin apply for mod presencefootsteps failed presencefootsteps.mixin.json:compat.create.MEntity from mod presencefootsteps -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method forCollision in presencefootsteps.mixin.json:compat.create.MEntity from mod presencefootsteps was not located in the target class net.minecraft.world.entity.Entity. Using refmap presencefootsteps.mixin.refmap.json Method is @Dynamic(forCollission(center, consumer) - Private member injected by Create. See: https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/foundation/mixin/client/EntityContraptionInteractionMixin.java#L81C21-L81C21)

Latest Log:
[latest.log](https://github.com/user-attachments/files/16926490/latest.log)

Crash Log:
> Not generated due to early crash

**Comment by Mickeon** [comment]
I confirm this bug is occurring to me as well.

**Comment by DeshiDesu** [comment]
Thanks for the fix

**Comment by Mickeon** [comment]
It's been fixed in https://github.com/Sollace/Presence-Footsteps/commit/f53f65da2e582efeaad8b37662ebc4c408e4f6f4 . Just because there's no new release of the mod doesn't mean it hasn't been fixed.
