### ISSUE TITLE
Entity that comes from enlightenend elicits a error 

### ISSUE THREAD

**Issue by NeoStarWonV** [Sollace/Presence-Footsteps#339]
[crash-2024-09-21_22.17.41-client.txt](https://github.com/user-attachments/files/17084451/crash-2024-09-21_22.17.41-client.txt)

**Comment by Sollace** [comment]
You are using an old version of Presence Footsteps, also one of the mods you have is not correctly configuring the sounds for its block. I'm going to fix this specific crash, but just as an fyi I can't guarantee it won't still have issues with that combination of mods.

I'd recommend if you can find which mod is causing this that you also report it as a bug to them.
