### ISSUE TITLE
Presence Footsteps removes skin transparency restrictions

### ISSUE THREAD

**Issue by Khodyn** [Sollace/Presence-Footsteps#34]
When this mod is installed in 1.15.1, it removes skin transparency restrictions on the base layer.
With:
![image](https://user-images.githubusercontent.com/49518050/71226772-2e935a80-2331-11ea-96ac-7ad20e1c9237.png)

Without:
![image](https://user-images.githubusercontent.com/49518050/71226707-e5dba180-2330-11ea-9ec8-3293617e94bd.png)
It actually kinda got my hopes up until I realized it was just a bug from this mod. 😞

**Comment by Sollace** [comment]
Not an intended feature, but also not a bug either. PF shares a library with Mine Little Pony where one of the documented features is working transparency in player skins.
