### ISSUE TITLE
[info request] Sound source/license

### ISSUE THREAD

**Issue by drakomatic** [Sollace/Presence-Footsteps#340]
I really like the sounds from this mod and I wanted to know more information about where they're from and what I can do with them.

I saw you said somewhere that you're okay with other people using the sounds from the mod but I'd like to know where you draw the line (Does my project have to open source or free? can I use them in a paid product?)

Thanks in advance!

**Comment by DeshiDesu** [comment]
> I really like the sounds from this mod and I wanted to know more information about where they're from and what I can do with them.
> 
> I saw you said somewhere that you're okay with other people using the sounds from the mod but I'd like to know where you draw the line (Does my project have to open source or free? can I use them in a paid product?)
> 
> Thanks in advance!

All sounds are open source: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound
Enjoy including these sounds into any project as I have done

**Comment by Sollace** [comment]
The sounds are essentially all public domain, though I don't have sources for them unfortunately. They were mainly sourced by Huricaaan and (if I remember correctly) what they told me was that they got the sounds from some public sound effects websites.

**Comment by drakomatic** [comment]
Thanks for the info, marking this as closed.
