### ISSUE TITLE
Random Footstep SFX Playing When Player Under Blocks (Schizophrenia)

### ISSUE THREAD

**Issue by AlexzanderGreats** [Sollace/Presence-Footsteps#341]
Version: PresenceFootsteps-1.10.0+1.21

Issue in Depths: When the player stands under blocks, footstep SFX play at random and unrelated and independently to the player's presence in the world. Coming from above and all around the player.

**Comment by AlexzanderGreats** [comment]
Here's a video of the issue:

https://github.com/user-attachments/assets/17f9d6c4-33b8-410e-959a-2e83e710df26

**Comment by Sollace** [comment]
This is weird. Seems like it's playing sounds from the block you're looking at.

I'll see if maybe it was something left in when I made the release.

**Comment by AlexzanderGreats** [comment]
Thank you very much, I love your ambiance mod, and I look forward to updates in the future (=

**Comment by Sollace** [comment]
Cannot reproduce in multiplayer either, I'm afraid.

**Comment by AlexzanderGreats** [comment]
Strange, are you on the same mod version?

**Comment by Sollace** [comment]
> Strange, are you on the same mod version?

Yeah. Only thing I can think is it's not working because I'm testing on a local lan and the host has the mod too.

I'll have to set up a proper testing scenario later so I'm holding off on releasing updates until I can.

**Comment by AlexzanderGreats** [comment]
I could probably try to send my config of the mod, though it might be an incompatibility with Lunar client of some kind

**Comment by Sollace** [comment]
I cannot reproduce this under any circumstance even with a vanilla server, so I'm gonna have to say it might be your client or another mod that's causing this.
