### ISSUE TITLE
Could you please add the NeoForge tag to your mod?

### ISSUE THREAD

**Issue by DarthCaesium** [Sollace/Presence-Footsteps#345]
I'm trying to make a NeoForge modpack on CurseForge that includes your mod, but CurseForge requires any Fabric mod to be tagged for NeoForge in order to use it with Sinytra Connector and publish the modpack.

**Comment by Sollace** [comment]
The mod is made to run on fabric. I cannot add the NeoForge tag as that would be untrue.
