### ISSUE TITLE
Crash on startup with newest version (1.10.0) for fabric 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [Sollace/Presence-Footsteps#349]
[crash-2024-11-21_12.16.56.5214-quilt_loader.txt](https://github.com/user-attachments/files/17850317/crash-2024-11-21_12.16.56.5214-quilt_loader.txt)

**Comment by Sollace** [comment]
I've made another update to remove the create support. The new version should fix the crashing issue.

https://github.com/Sollace/Presence-Footsteps/releases/tag/1.10.1%2B1.20.1
