### ISSUE TITLE
[Fabric] Mixin Conflict with Create

### ISSUE THREAD

**Issue by Soyvolon** [Sollace/Presence-Footsteps#351]
# Summary

Seems to be a mixin conflict with Create Fabric on a `forCollision` method.

# Details
Minecraft Version: 1.20.1
Fabric Version: fabric-0.16.9

## Mods
Fabric API (`fabric-api-0.92.2+1.20.1.jar`)
Presence Footsteps (`PresenceFootsteps-1.9.4+1.20.1.jar`)
Create Fabric (`create-fabric-0.5.1-j-build.1604+mc1.20.1.jar`)

# Error

```
Mixin apply for mod presencefootsteps failed presencefootsteps.mixin.json:compat.create.MEntity from mod presencefootsteps 
    -> net.minecraft.class_1297: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException 
    @Shadow method forCollision in presencefootsteps.mixin.json:compat.create.MEntity from mod presencefootsteps 
    was not located in the target class net.minecraft.class_1297. Using refmap presencefootsteps.mixin.refmap.json 
    Method is @Dynamic(forCollission(center, consumer) - Private member injected by Create. See: 
    https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/foundation/mixin/client/EntityContraptionInteractionMixin.java#L81C21-L81C21)
```
(full log: [latest.log](https://github.com/user-attachments/files/17972240/latest.log))

# Testing Pack (Curse Forge)

If you use Curse Forge, here is a testing pack containing just the listed mods above: [Footsteps_Create Crash Test.zip](https://github.com/user-attachments/files/17972269/Footsteps_Create.Crash.Test.zip)

**Comment by Sollace** [comment]
Update presence footsteps.

https://github.com/Sollace/Presence-Footsteps/releases/tag/1.10.2%2B1.21.3
