### ISSUE TITLE
Player skins are removed

### ISSUE THREAD

**Issue by srnyx** [Sollace/Presence-Footsteps#354]
Using 0.10.3+1.20.4 (didn't test other 0.10.3 versions), all player skins (including yourself) are replaced with Steve/Alex
![image](https://github.com/user-attachments/assets/1b001aa9-15f9-4cf0-a506-ae1d25072070)

Occurs with fresh install of Presence Footsteps (and Fabric API)

**Comment by Sollace** [comment]
Are you sure you're using 1.20.4?

**Comment by srnyx** [comment]
> Are you sure you're using 1.20.4?

Sorry, I meant 1.21.4 hahah

**Comment by Sollace** [comment]
Okay, yeah. Looks like a bug in the 1.21.4 version of kirin. I'll get an update out soon

**Comment by Sollace** [comment]
https://github.com/Sollace/Presence-Footsteps/releases/tag/1.10.4%2B1.21.4
