### ISSUE TITLE
[Bug Report] Changing #minecraft:nylium tags' sounds in texture packs breaks things

### ISSUE THREAD

**Issue by dotCatshark** [Sollace/Presence-Footsteps#356]
As per title. I'll explain what I mean in greater detail.

Crimson nylium and warped nylium are not explicitly referenced in the blockmap.json. It uses the tag #minecraft:nylium twice in two completely different spots. Changing the sounds that are defined to, say, mushroom + grass, does not do anything. The sounds stay as mud + slick (which drives me crazy because it's supposed to be a fungus). Additionally, removing the two tags and replacing them with individual references causes the resourcepack to simply just, not work all the sounds (even previously working ones) will revert to their default.

It might be because of my horrendous syntax and poor practice but I'm going to go off on a limb and say this isn't intended behavior. Am I doing something wrong, or is this an uncaught bug?

**Comment by Sollace** [comment]
You'd need to provide your blockmap before I can what might be happening.

**Comment by dotCatshark** [comment]
Post Holiday Update:

Issue seems to have mysteriously fixed itself with zero input or updates on my part. I can't replicate it so it'll have to remain a mystery. Call it a christmas miracle.

**Comment by Sollace** [comment]
Okay! I'll close this for now then. If the problem comes back you can come back here.
