### ISSUE TITLE
Could not find required mod: presencefootsteps requires {kirin @ [*]}

### ISSUE THREAD

**Issue by cal3432** [Sollace/Presence-Footsteps#36]
Could not find required mod: presencefootsteps requires {kirin @ [*]}

**Comment by cal3432** [comment]
I have fabric api installed.

**Comment by Sollace** [comment]
Kirin is bundled inside presence footsteps. The only reason it wouldn't load is because of a probme with your environment.

Either you didn't install fabric-api, didn't update fabric-api, or didn't update fabric-loader when you updated the game.

I suggest you try that last thing.

**Comment by cal3432** [comment]
Tried, fabric api is right version, launcher is fine. Nothing wrong with me.
