### ISSUE TITLE
If the original mod wasn't forge compatible then why does it say so on the website?

### ISSUE THREAD

**Issue by i-o-u** [Sollace/Presence-Footsteps#39]
[The website](https://minecraft.ha3.eu/presencefootsteps) and [the minecraft forums page](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound)
![Screenshot (49)](https://user-images.githubusercontent.com/60834747/74124025-eacc1b80-4c24-11ea-99db-72f01f82a228.png)

**Comment by Sollace** [comment]
Liteloader can be installed with forge. Hence you could install this mod with forge by using liteloader.

Please stop making these issue. My decision is final.
