### ISSUE TITLE
Do footsteps play from other players?

### ISSUE THREAD

**Issue by InfoTeddy** [Sollace/Presence-Footsteps#40]
I don't know how to verify this on my own, but from what I can tell, with this mod installed, other players in multiplayer don't play footsteps. Not *just* not Presence Footsteps footstep sounds, not even vanilla footstep sounds.

**Comment by Sollace** [comment]
No, they do not. The mod doesn't really handle anything other than your own player.

I have considered it as a possible enhancement, but never got to actually doing it/forgot in the interim.

**Comment by InfoTeddy** [comment]
Ok. Is there a way to at least make it so that other players play vanilla footstep sounds?

**Comment by Sollace** [comment]
Do they play sounds in vanilla? I don't really want to mess with stuff that's outside the mod's scope.

**Comment by InfoTeddy** [comment]
Yes, they play sounds in vanilla.

**Comment by Sollace** [comment]
Fixed in 1.16
