### ISSUE TITLE
Some blocks dont have custom sounds

### ISSUE THREAD

**Issue by RyanCR03** [Sollace/Presence-Footsteps#41]
they make the sounds play the same footstep sounds for major footstep sounds (running, walking, landing) and minor footstep sounds (strafing, jumping). these sounds were detected in lanterns, scaffold, sea pickles, and heads.

**Comment by Sollace** [comment]
This is intentional for the default sounds pack. All of those blocks have "special" sounds in vanilla that aren't easily reproduced, and fit them much better than PF can come up with on its own, so I rather leave their sounds alone.
