### ISSUE TITLE
Multiplayer footsteps for 1.15.2

### ISSUE THREAD

**Issue by JackDainzh** [Sollace/Presence-Footsteps#42]
Since it was realised in r23 for snapshot version, could you possible implement the same thing with 1.15.2 version, please?

**Comment by Sollace** [comment]
I'll test it in 1.15.2. Normally I don't like porting stuff back.

**Comment by Sollace** [comment]
Done: https://github.com/Sollace/Presence-Footsteps/releases/tag/r23-1.15.2

**Comment by JackDainzh** [comment]
Thank you very much!
