### ISSUE TITLE
[r23 | 1.15.2] Multiplayer footsteps are duplicated & buggy

### ISSUE THREAD

**Issue by Swordee** [Sollace/Presence-Footsteps#43]
## Description
When two players (or possibly more - haven't tested) are on the same block walking, it glitches out the sound to be duplicated and even continue when the player is no longer on that surface.

## Version
- PresenceFootsteps-r23+1.15.2

##  Installed Mods
- Apple Skin
- Audio Output
- Beenfo
- Clear Skies
- Dev World
- Fabric API
- Voxel Map
- FrameThrough
- Held Item Info
- Horse Stats Vanilla
- Mambiance (possible conflicting mod?)
- Mod Menu
- OkZoomer
- OptiFabric
- Pling
- OptiFine 1.15.2 pre12
- Random Block Placement
- Shulker Box Tooltip
- Void Fog

**Comment by JackDainzh** [comment]
Can agree, this happens now, and players don't emmit sounds when they walk too.

**Comment by Sollace** [comment]
Works as intended

**Comment by Sollace** [comment]
@JackDainzh Make sure the mode is set to "Multiplayer" in the mod's settings screen.
