### ISSUE TITLE
r23-1.15.2 Sound bugs. (not directional). 

### ISSUE THREAD

**Issue by JackDainzh** [Sollace/Presence-Footsteps#44]
Sorry for coming up again, but this time i made a small video presenting the sound issue:
https://youtu.be/1_HBgkAb5to
These are the settings i am using:
![image](https://user-images.githubusercontent.com/44118724/78423300-13452480-766e-11ea-845a-d501ec6a6d74.png)
So the problem with player collision persists and what's more important sound is not directional, it means no matter where the other player is it will play everywhere.

**Comment by JackDainzh** [comment]
Tester with and without Mambience mod, no change.

**Comment by xAlicatt** [comment]
Can confirm. Was coming to see if this was a bug or if I was crazy. :D

**Comment by Sollace** [comment]
Fixed in this evening's build.
