### ISSUE TITLE
[Suggestion] Add support to mod blocks with vanilla tags

### ISSUE THREAD

**Issue by Samekichi** [Sollace/Presence-Footsteps#51]
Presence Footsteps is fantastic in vanilla games but I'not sure if it can be implemented to some mod blocks, at least to those with vanilla tags, for a more universal implementation. 
For instance, many biome mods add various leaf blocks with a vanilla tag #leaves, so is there possibility for Presence Footsteps to automatically play sound when stepping on them the same as on vanilla leaves?

**Comment by Sollace** [comment]
All of presence footsteps can be configured using a resourcepack, including support for mod blocks, entities, and sounds.

https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators
