### ISSUE TITLE
1.16.2 support

### ISSUE THREAD

**Issue by MeikelLP** [Sollace/Presence-Footsteps#56]

**Comment by MeikelLP** [comment]
@Sollace I guess that's a "No I won't support 1.16.2"?

**Comment by Sollace** [comment]
A 1.16.2 version will be released regardless of whether you ask for one. Creating issues and bugging me about it is not going to make it any faster though.

**Comment by MeikelLP** [comment]
Last update is ~1.5 months old. So this was just to check whether this project is still alive.

**Comment by Sollace** [comment]
It's okay. I assure you I don't have any intention of abandoning any of my projects. So long as I'm still the contributor to https://github.com/MineLittlePony everything downstream to it will eventually get an update (time permitting).
