### ISSUE TITLE
Is this mod fabric (no forge versions) only?

### ISSUE THREAD

**Issue by jakey1995abc** [Sollace/Presence-Footsteps#59]
I couldn't leave a comment on the project page so using this instead. Is the project for fabric only, or is there support for forge? Only asking as I couldn't find any mention of either in the project's description.

**Comment by Sollace** [comment]
It's tagged as a fabric mod on curseforge, so... Yes?
![image](https://user-images.githubusercontent.com/6429283/91823549-a8f2d900-ec39-11ea-896a-55b0800c36ce.png)
