### ISSUE TITLE
Suggestion: add a volume slider for footsteps to the sound options GUI

### ISSUE THREAD

**Issue by SoullessWaffle** [Sollace/Presence-Footsteps#6]
The sounds this mod adds can be really loud compared to vanilla sounds when you've got some of the vanilla volume sliders turned down. Currently the only way to change the volume is by adjusting the master volume, which is unfortunate because this also turns down all other sounds.

**Comment by Sollace** [comment]
Press F9 (configurable in settings) to adjust the volume and other settings.

**Comment by SoullessWaffle** [comment]
Oh, whoops! Thanks.
