### ISSUE TITLE
[Suggestion] Backport r28 (1.16.2) to 1.16.1?

### ISSUE THREAD

**Issue by Abbanon** [Sollace/Presence-Footsteps#61]
I humbly request a backport of the latest 1.16.2 build (r28) into 1.16.1, because it currently does not support it.
Having the patches and bugfixes from it would be great. Would it be possible?

**Comment by Sollace** [comment]
I recommend updating to 1.16.2 (or 1.16.3). There's no reason not to, and I'm not going to support outdated versions.
