### ISSUE TITLE
[Suggestion] Wet footsteps

### ISSUE THREAD

**Issue by AtomPlayz** [Sollace/Presence-Footsteps#63]
Hello, so I'm not sure if you already got this suggestion but I'm gonna put it. Could you make wet footsteps while it rains or you're walking in water? It would be really realistic and cool. If you already saw a suggestion or question like this or already had plans for this, sorry!

**Comment by Sollace** [comment]
I will have to think about this. What your suggesting sounds like it would be more fitting in Matmos, however since I'm not actively updating that, maybe it could find a home here in PF.

**Comment by AtomPlayz** [comment]
Ah, okay. Thanks for the response.
