### ISSUE TITLE
footsteps dont match placing sounds

### ISSUE THREAD

**Issue by RyanCR03** [Sollace/Presence-Footsteps#65]
the pf sounds for the new 1.16 blocks(and some older ones) don't match the sounds they make when placed

shroomlight place sound: hollow, a bit crumbly, a little moist maybe.
shroomlight pf: squishy, wet. best alternative: mushroom, dirt

bone block place sound: solid, healthy.
bone block pf: cracky thin, should drink more milk. best alternative: sandstone, 1.16 bone block step sound

nether wart blocks place sound: dry, probably flaking off.
nether wart blocks pf sound: wet, squishy. best alternative: snow, 1.16 nether wart block step sound

(btw the chain landing sound has now impact.)

**Comment by Sollace** [comment]
My reasoning for having the sounds as they are is that when you're walking on them (the bones in particular) you're placing your weight on them, which causes them to compress and make the different sounds you hear.

Bones crack, organics (pumpkins, nether wart, shrooms, etc) get squished, maybe bruised, etc.

Can you clarify on chains?

**Comment by RyanCR03** [comment]
chains sound like you are just shaking them instead of landing on it and also I just thought a lot of the nether blocks sound wet when there shouldn't be anything wet in the nether

**Comment by RyanCR03** [comment]
maybe you could add a configuration to change the sounds that play on some blocks. as resourcepacks can make blocks look like they are made of different materials

**Comment by Sollace** [comment]
You can already customise the entire mod using resourcepacks. https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators

**Comment by RyanCR03** [comment]
i cant figure out how to get the custom pf sounds
