### ISSUE TITLE
Do you plan to add sounds to the blocks from mods like BYG, Terrestria, Traverse?

### ISSUE THREAD

**Issue by RDKRACZ** [Sollace/Presence-Footsteps#66]
I'm asking because it's weird when you are walking on biomes from mods and there is no sound then you step on vanilla biome and you hear every block

**Comment by Sollace** [comment]
This question has been asked before. Anyone can make sound packs for their favourite mods. Just refer to the [guide](https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators)
