### ISSUE TITLE
Issue with latest 1.8.9 MAtmos release: resource packs are for 1.9

### ISSUE THREAD

**Issue by SoullessWaffle** [Sollace/Presence-Footsteps#7]
I wasn't sure where to put this because [Sollace/MAtmos](https://github.com/Sollace/MAtmos) has no issues tab.

I downloaded `Matmos.Default.zip` and `MSI.Conversion.zip` from the [latest 1.8.9 release](https://github.com/Sollace/MAtmos/releases/tag/r29b) and put them in my `/resourcepacks` folder, but Minecraft is telling me that they are for an updated version of Minecraft (presumably 1.9).

**Comment by SoullessWaffle** [comment]
It does appear load and work fine though. I guess you could add a note to the release letting people know the resource packs do work.

**Comment by Sollace** [comment]
Yeah that's fine. The contents of the resourcepacks between 1.8 and 1.9 are exactly the same, it's just that older versions will complain because the resourcepacks have a compatibility value for 1.9.

**Comment by SoullessWaffle** [comment]
Alright, I'll close this issue then. Are GitHub issues disabled on the [MAtmos repo](https://github.com/Sollace/MAtmos) for a reason btw? If not, you can do the opposite of _[this](https://help.github.com/articles/disabling-issues/)_ to re-enable them.

**Comment by Sollace** [comment]
Nah, I just didn't think they would be needed.

I actually don't intend to keep Matmos. I just did the update to 1.9
