### ISSUE TITLE
Support for wading would be great

### ISSUE THREAD

**Issue by FewerFlaws** [Sollace/Presence-Footsteps#70]
I have cattails from terrestria that grow in the water.  I've got a bit of sound coming from them when I jump around, but it certainly doesn't feel right when I'm slogging through them quietly using these settings.
![2020-12-28_23 38 34](https://user-images.githubusercontent.com/75643699/103267752-18b66d80-4967-11eb-9be1-71d85149178c.png)

**Comment by FewerFlaws** [comment]
This is what I'm doing for them currently:
	"terrestria:cattail": "brush_straw_transition",
	"terrestria:cattail.messy": "brush_straw_transition",
	"terrestria:cattail.foliage": "brush_straw_transition",
	"terrestria:tall_cattail": "brush_straw_transition",
	"terrestria:tall_cattail.messy": "brush_straw_transition",
	"terrestria:tall_cattail.foliage": "brush_straw_transition",

**Comment by Sollace** [comment]
How would the wading work? Is the player in the water block below the cattails?

**Comment by Sollace** [comment]
You can try adding your own sounds using the acoustics.json. There's no documentation for it in the wiki yet, but the mod's own acoustics file should give you enough to piece together your own and you can specify which sounds exactly to use under which circumstances.

    "brush": {
      "walk": {
        "name": "brush.brush_through",
        "vol_min": 65,
        "vol_max": 65
      },
      "wander": {
        "name": "brush.brush_through",
        "vol_min": 65,
        "vol_max": 65
      },
      "jump": {
        "name": "brush.brush_through",
        "vol_min": 65,
        "vol_max": 65
      },
      "land": {
        "name": "brush.brush_through",
        "vol_min": 65,
        "vol_max": 65
      }
    }

**Comment by FewerFlaws** [comment]
Oh, I didn't see your question there until now.  In this case the base of the cattails share the space with the water and the player would be walking through that same water block.  I'm going to see if any of the motion types you linked here make the cattails audible =]

**Comment by Sollace** [comment]
> cattails are in the water block
Oh, I see. In that case I may have to do a little poking around myself as the same may apply to underwater plants in vanilla.

There may also be a "swim" motion type which would be applied when the player is in the water.

**Comment by FewerFlaws** [comment]
Using every option available I'm able to produce sound from the cattails when:
  * Interesecting them with my character model while standing on an adjacent grass block.
  * Pressing the jump key to start swimming up while wading.  This only works if my feet are touching the very bottom.

So it's still completely silent to wade through the cattails and to leap into them without touching nearby solid blocks.

**Comment by FewerFlaws** [comment]
Carpet and foliage are able to produce sound, with carpet overriding foliage.  Neither of them work when simply moving through the space though.  They'll only trigger when "jumping" to start swimming up.

**Comment by Sollace** [comment]
Next release should have this scenario work a lot better. You shouldn't have to change anything on your side.

Something like this:

	"terrestria:cattail": "NOT_EMITTER",
	"terrestria:cattail.messy": "MESSY_GROUND",
	"terrestria:cattail.foliage": "brush_straw_transition",
