### ISSUE TITLE
Is it possible with resource packs to remove some of the wander sounds?

### ISSUE THREAD

**Issue by SpacEagle17** [Sollace/Presence-Footsteps#73]
I don't like how some wander sounds sounds, what i always do when a new version of the mod releases is to extract the jar file and delete the wander sounds in the file sounds.json. Is it possible to remove those sounds with a resource pack? Great mod

**Comment by Sollace** [comment]
You probably could by adding your own acoustics.json that overwrites the entries that you want to remove wandering aounds from.
