### ISSUE TITLE
Strange WARN in log caused by Presence Footsteps - Something about SemVer?

### ISSUE THREAD

**Issue by Abbanon** [Sollace/Presence-Footsteps#75]
I've noticed a strange WARN related to this mod in my logs:

> **``[main/WARN]: Mod `presencefootsteps` (r29+1.16.4) does not respect SemVer - comparison support is limited.``**

Is this something that can be ignored?

**Comment by Sollace** [comment]
SemVer is Semantic Versioning. It requires a very specific format for the version number which we do not use.

The message is a warning so you can just ignore it.
