### ISSUE TITLE
Other sounds cuts out

### ISSUE THREAD

**Issue by Brottweiler** [Sollace/Presence-Footsteps#8]
You know how other sounds gets cut off or are silent when there's a lot of sounds like fire or blazes around? This is happening with Presence Footsteps, I suppose maybe it's because everyone else has the PR footsteps sounds now.

**Comment by Sollace** [comment]
Yeah, that's an unfortunate side-effect. Not something I can fix though. Mojang has to fix their sound system to blend sounds.

**Comment by Brottweiler** [comment]
@Sollace Can you add a toggle setting for enableing and disableing PR for other players? If there's 1 player around I think it won't happen, but if there's 10 or more around it does.

**Comment by Sollace** [comment]
Sure. I'll put that in next time I have the chance.
