### ISSUE TITLE
Avian stance implies quadruped

### ISSUE THREAD

**Issue by griffin4cats** [Sollace/Presence-Footsteps#80]
This is less of a bug and more of a suggestion.
The only stances that are valid are biped, quadruped, and winged quadruped (avian).
It would be nice to have a winged biped mode to better suit some playstyles, including my own. As such a winged biped mode would be greatly appreciated.

**Comment by Sollace** [comment]
Quad and Winged Quad are added for the player to accompany the Mine Little Pony mod. Quad being for moat ponies and winged quad for pegasi and alicorns.

Thus I don't really see the reason you would want the winged without the quad here.

**Comment by griffin4cats** [comment]
My skin has wings, I don't really know anything about Mine Little Pony. 
Here's my skin in-game, for reference (I'm also using the Ears mod)
![image](https://user-images.githubusercontent.com/62814690/107862038-88959000-6e0f-11eb-8c25-b849d463c712.png)
It just seems natural to me that there'd be an avian biped mode.
