### ISSUE TITLE
Presence-Footsteps turns transparent skins transparent instead of black

### ISSUE THREAD

**Issue by ZtereoHYPE** [Sollace/Presence-Footsteps#82]
As explained in the title, presence-footsteps seems to change the player rendering to be transparent on areas where pixels are transparent instead of black like in Vanilla. This can be an issue because some players might put on a completely transparent skin and thus turn completely invisible to the player.

## Screenshot of fabric installation with only Fabric API (looks identical to Vanilla):
![2021-02-17_11 43 42](https://user-images.githubusercontent.com/57519662/108193773-1a561380-7116-11eb-9148-27c6fb18654a.png)

## Screenshot of same installation, but with Presence-Footsteps added to it:
![2021-02-17_11 44 44](https://user-images.githubusercontent.com/57519662/108193899-41144a00-7116-11eb-99ef-38f9033ee673.png)

**Comment by CalXee** [comment]
Still baffling how a sound mod introduces such a bug...

**Comment by ZtereoHYPE** [comment]
> Still baffling how a sound mod introduces such a bug...

I know right? It took me a long time to figure out it was this mod's fault simply because i just didn't think it could have had an effect

**Comment by Sollace** [comment]
This is an intentional change made by a pre-requisite mod PF uses (that's also part of Mine Little Pony and HDSkins) -> https://github.com/MineLittlePony/Kirin/blob/2bbe8316b685a09e3c1901dfc3506c86973d634c/src/main/java/com/minelittlepony/common/mixin/MixinPlayerSkinTexture.java#L36
