### ISSUE TITLE
1.16.5 Availability

### ISSUE THREAD

**Issue by jakey1995abc** [Sollace/Presence-Footsteps#83]
Is this mod still compatible with 1.16.5? If so could you add the tag for it so that CurseForge client users can find and add the mod to their packs?

**Comment by Sollace** [comment]
This mod does indeed work in 1.16.5, as do most 1.16.x mods made for fabric.

I can't tag another minecraft version without doing another release.

**Comment by jakey1995abc** [comment]
> This mod does indeed work in 1.16.5, as do most 1.16.x mods made for fabric.
> 
> I can't tag another Minecraft version without doing another release.

Oh, I've never seen this issue before. You should be able to edit the file's tags on the CurseForge website to include newer versions of Minecraft if compatible (many other devs do this). Just thought I'd let you and a few other devs know that their tags were outdated, as the mods won't show up for people creating custom modpacks with the latest version of Minecraft in CurseForge otherwise :)
