### ISSUE TITLE
ArrayIndexOutOfBoundsException when entering the Nether

### ISSUE THREAD

**Issue by SoullessWaffle** [Sollace/Presence-Footsteps#9]
I'm on Minecraft 1.8.9, using both Presence Footsteps and MAtmos.
The crash happened when I entered the Nether through a vanilla Nether portal.

Crash log: http://pastebin.com/YvefuGpY

Edit: this bricks the save too. I guess it doesn't like the Nether's dimension ID (-1)

**Comment by Sollace** [comment]
Should be fixed now.

**Comment by SoullessWaffle** [comment]
Hey, sorry to bother you again but how do I update the mod?

I downloaded the new `presencefootsteps-u9c.litemod` file from the releases page and put it in my `/mods/1.8.9` folder, then I moved the old file out of the folder and launched Minecraft. But now when I check the Liteloader panel it doesn't show the mod there. It says two mods are loaded (MouseTweaks and MAtmos) but Presence Footsteps is not listed anywhere. Am I missing something?

**Comment by Sollace** [comment]
Any u9 versions only work with minecraft 1.9.

You have to get the u8 to play in 1.8.9. Those versions will also be updated with bug fixes as needed. (u8e is currently the newest for that minecraft version)

**Comment by SoullessWaffle** [comment]
Oh, my bad. I could swear I downloaded the .litemod for the latest 1.8.9 release, but I guess I misclicked :P

**Comment by Sollace** [comment]
Alrighty. I did make it a bit clearer to see which is witch. :P
