### ISSUE TITLE
Where are the assets?

### ISSUE THREAD

**Issue by Riteo** [Sollace/Presence-Footsteps#90]
Sorry if this may not actually be a proper issue, but I can't find any other way to contact you.
I usually compile all my mods out of habit. I compiled your mod and it gave a lot of weird errors talking about missing files.
That sounded weird, so I looked in the source and actually it doesn't have any audio file in there, but your precompiled releases do.

Is there some reason for that? Why are the assets of the audio pack missing?

**Comment by Sollace** [comment]
The audio files are not actually included as part of the repository as they would otherwise make it too large to work with. If you need them to build the mod yourself, you'll have to extract them from a pre-built version. Sorry!

**Comment by Riteo** [comment]
@Sollace I see, no worries then! If you could include them in the release files, or even make a designated repo that would be cool, altough I can understand if you don't care, mine is a very niche practice.
