### ISSUE TITLE
Cauldrons with water

### ISSUE THREAD

**Issue by Riteo** [Sollace/Presence-Footsteps#91]
Would it be possible to add sounds to the water inside a cauldron? That'd be very cool! Since it doesn't have a physics response I don't know if you could do that easily though.

**Comment by Sollace** [comment]
I did experiment with trying something like this, but the result was somewhat weird. When you stepped on the rim (edge) of the cauldron it would produce water sounds, which, imo, isn't correct.

**Comment by Riteo** [comment]
@Sollace yeah I agree, that wouldn't sound right. Wouldn't there be a way to limit the sound only to the bottom of the inside? I don't know how this mod works. No worries if there's no easy way.

**Comment by Sollace** [comment]
Closing this, since there's no easy way I can think of to do water sounds for the cauldron that wouldn't be out of place.
