### ISSUE TITLE
No audio files?

### ISSUE THREAD

**Issue by BrekiTomasson** [Sollace/Presence-Footsteps#92]
Looping back to the question raised in #90 , which was closed without any real answer - Is there any (good) reason for why the audio files are not included here? We're only talking about about 7 megabytes. Not including them makes it incredibly difficult for people to help out with pull requests, bug fixes or making other small tweaks.

**Comment by Sollace** [comment]
Git wasn't built to handle binary files very well. It can't track changes in them and they just cause the repository to grow in size. Huricaaane had already decided to keep them excluded and I agreed with his decision to do so, so I've done the same here.

Again, if you need the audio files _they are in the released version of the mod_.

You can extract them and use them. The audio files don't change very often, and this repository is more about maintaining the code than the assets.

**Comment by Riteo** [comment]
@Sollace
> Git wasn't built to handle binary files very well.

That's a pretty good point, but you could make a simple repo designated just for that.
Also you could link it in the resources folder if that turns out to work out-of-the-box.

**Comment by Sollace** [comment]
Audio files are now listed in the 1.18 branch.
