### ISSUE TITLE
Java wont open when trying to install 

### ISSUE THREAD

**Issue by Luca6731** [Sollace/Presence-Footsteps#94]
How do i properly install this mod? when trying to open with java, java wont open? my java works as i used it to install optifine minutes before

**Comment by Sollace** [comment]
Optifine is a special case. You shouldn't be trying to open the mod with Java.

Instead install Fabricloader and put the jar file for this mod and fabric-api into your mods folder. The folder should be created when launching the game after installing fabricloader.

You can follow the same steps for installing Mine Little Pony (linked here: https://github.com/MineLittlePony/MineLittlePony/releases/tag/1.17-4.3) Just skip the part about installing HD Skins.

Also for optifine search on google for "Optifabric" to find a compatible version you can use with fabricloader, as the regular optifine will not work.
