### ISSUE TITLE
[Bug Report] Release 1.17 - "PresenceFootsteps-r30-1.17-rc1" crashes on launch

### ISSUE THREAD

**Issue by Abbanon** [Sollace/Presence-Footsteps#95]
As the title says, the game has a fatal crash error on launch when using `PresenceFootsteps-r30-1.17-rc1` on official release 1.17.

Log: https://paste.ee/p/plrgr

**Comment by Sollace** [comment]
I am aware of the issue with Kirin. It's affecting a few mods that us the lib and I'll be looking at fixing it soon!

**Comment by Sollace** [comment]
This issue has now been fixed! You can download the new version (r31) from over [here](https://github.com/Sollace/Presence-Footsteps/releases/tag/r31)

Sorry about that!
