### ISSUE TITLE
Crash when using the "hookshot" mod

### ISSUE THREAD

**Issue by DSRoie** [Sollace/Presence-Footsteps#98]
It just dropped everyone who listened,and they can reconnect back quickly. The server did not crash, and there was no feedback or error message,so this should be a local error.
Maybe it conflicts with the sizzle when the hook is retracting? I'm not sure.
→→→this mod:https://www.curseforge.com/minecraft/mc-mods/hookshot

**Comment by DSRoie** [comment]
I also reported this error on the "hookshot" page:https://github.com/CammiePone/Hookshot/issues/13

**Comment by Sollace** [comment]
This is a client-only mod and I don't do anything that interacts with entity loading or saving, or with their logic.

Additionally the exception is coming entirely from Hookshot's code in the server logic, so it's unlikely this mod would have anything to do with this.

**Comment by XanaDublaKublaConch** [comment]
I just ran into the same issue. On a brand new server world, if I log in by myself with both mods enabled, /give myself a hookshot, and fire it, I get disconnected as soon as the hookshot hits a hookable block. There is no error on the client or server. When I log back in, I land back where I was standing as if I had been hovering an inch off the floor. If I remove Presence Footsteps, the hookshot works fine.

**Comment by Sollace** [comment]
@XanaDublaKublaConch https://github.com/Sollace/Presence-Footsteps/releases/tag/r32
